
import type { PokemonCard } from './types';

// McDonald's Dragon Discovery Set Cards
// Image URLs from Pokellector: https://den-cards.pokellector.com/MCD24/{CardName}.MCD24.{CardNumber}.png
// Pokedex number is the card number in this specific set.

export const mcDonaldsDragonDiscoveryCards: PokemonCard[] = [
  {
    id: 'mcd-dragon-dratini-001', // Pokellector lists Dratini as 2/12, Dragonair as 1/12. Let's follow set order for ID.
    name: 'Dratini',
    image: 'https://den-cards.pokellector.com/MCD24/Dratini.MCD24.2.png',
    dataAiHint: 'Dratini dragon pokemon',
    rarity: 'Common',
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '2/12',
  },
  {
    id: 'mcd-dragon-dragonair-002',
    name: 'Dragonair',
    image: 'https://den-cards.pokellector.com/MCD24/Dragonair.MCD24.1.png',
    dataAiHint: 'Dragonair dragon blue',
    rarity: 'Common',
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '1/12',
  },
  {
    id: 'mcd-dragon-flaaffy-003',
    name: 'Flaaffy',
    image: 'https://den-cards.pokellector.com/MCD24/Flaaffy.MCD24.3.png',
    dataAiHint: 'Flaaffy electric sheep',
    rarity: 'Common',
    type: 'Lightning',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '3/12',
  },
  {
    id: 'mcd-dragon-goomy-004',
    name: 'Goomy',
    image: 'https://den-cards.pokellector.com/MCD24/Goomy.MCD24.4.png',
    dataAiHint: 'Goomy dragon slug',
    rarity: 'Common',
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '4/12',
  },
  {
    id: 'mcd-dragon-jangmo-o-005',
    name: 'Jangmo-o',
    image: 'https://den-cards.pokellector.com/MCD24/Jangmo-o.MCD24.5.png',
    dataAiHint: 'Jangmo-o dragon scales',
    rarity: 'Common',
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '5/12',
  },
  {
    id: 'mcd-dragon-latios-006',
    name: 'Latios',
    image: 'https://den-cards.pokellector.com/MCD24/Latios.MCD24.6.png',
    dataAiHint: 'Latios eon dragon',
    rarity: 'Uncommon', // Made Uncommon for pack variety
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '6/12',
  },
  {
    id: 'mcd-dragon-latias-007',
    name: 'Latias',
    image: 'https://den-cards.pokellector.com/MCD24/Latias.MCD24.7.png',
    dataAiHint: 'Latias eon dragon red',
    rarity: 'Uncommon', // Made Uncommon for pack variety
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '7/12',
  },
  {
    id: 'mcd-dragon-milcery-008',
    name: 'Milcery',
    image: 'https://den-cards.pokellector.com/MCD24/Milcery.MCD24.8.png',
    dataAiHint: 'Milcery cream fairy',
    rarity: 'Common',
    type: 'Fairy',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '8/12',
  },
  {
    id: 'mcd-dragon-riolu-009',
    name: 'Riolu',
    image: 'https://den-cards.pokellector.com/MCD24/Riolu.MCD24.9.png',
    dataAiHint: 'Riolu fighting puppy',
    rarity: 'Common',
    type: 'Fighting',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '9/12',
  },
  {
    id: 'mcd-dragon-slurpuff-010',
    name: 'Slurpuff',
    image: 'https://den-cards.pokellector.com/MCD24/Slurpuff.MCD24.10.png',
    dataAiHint: 'Slurpuff fairy cake',
    rarity: 'Common',
    type: 'Fairy',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '10/12',
  },
  {
    id: 'mcd-dragon-tatsugiri-011',
    name: 'Tatsugiri',
    image: 'https://den-cards.pokellector.com/MCD24/Tatsugiri.MCD24.11.png',
    dataAiHint: 'Tatsugiri dragon fish',
    rarity: 'Common',
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '11/12',
  },
  {
    id: 'mcd-dragon-cyclizar-012',
    name: 'Cyclizar',
    image: 'https://den-cards.pokellector.com/MCD24/Cyclizar.MCD24.12.png',
    dataAiHint: 'Cyclizar dragon lizard',
    rarity: 'Common',
    type: 'Dragon',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '12/12',
  },
];
