
import type { PokemonCard } from './types';

// Helper function to format card names for URLs
function formatNameForUrl(name: string): string {
  return name
    .replace(/'s/g, 's') // Ethan's -> Ethans
    .replace(/'/g, '')   // Remove other apostrophes
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/♂/g, '-M') // Male symbol
    .replace(/♀/g, '-F') // Female symbol
    .replace(/:/g, '')   // Remove colons
    .replace(/\./g, '')  // Remove periods (e.g., Lt.)
    .replace(/é/g, 'e')  // Pokémon -> Pokemon
    .replace(/#/g, '')   // Remove # if any
    .replace(/’/g, ''); // Remove right single quotation mark
}

const baseUniqueId = 57267;

export const destinedRivalsCards: PokemonCard[] = [
  {
    id: 'dri-ethans-pinsir-001',
    name: "Ethan's Pinsir",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ethan's Pinsir")}.DRI.1.${baseUniqueId + 1 - 1}.thumb.png`,
    dataAiHint: "Ethan Pinsir bug pokemon",
    rarity: 'Holo Rare',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '1/244',
  },
  {
    id: 'dri-yanma-002',
    name: 'Yanma',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Yanma")}.DRI.2.${baseUniqueId + 2 - 1}.thumb.png`,
    dataAiHint: 'Yanma bug flying pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '2/244',
  },
  {
    id: 'dri-yanmega-ex-003',
    name: 'Yanmega ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Yanmega ex")}.DRI.3.${baseUniqueId + 3 - 1}.thumb.png`,
    dataAiHint: 'Yanmega ex bug flying pokemon',
    rarity: 'Holo Rare',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '3/244',
  },
  {
    id: 'dri-pineco-004',
    name: 'Pineco',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Pineco")}.DRI.4.${baseUniqueId + 4 - 1}.thumb.png`,
    dataAiHint: 'Pineco bug pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '4/244',
  },
  {
    id: 'dri-shroomish-005',
    name: 'Shroomish',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Shroomish")}.DRI.5.${baseUniqueId + 5 - 1}.thumb.png`,
    dataAiHint: 'Shroomish mushroom pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '5/244',
  },
  {
    id: 'dri-breloom-006',
    name: 'Breloom',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Breloom")}.DRI.6.${baseUniqueId + 6 - 1}.thumb.png`,
    dataAiHint: 'Breloom mushroom fighting pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '6/244',
  },
  {
    id: 'dri-cynthias-roselia-007',
    name: "Cynthia's Roselia",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Cynthia's Roselia")}.DRI.7.${baseUniqueId + 7 - 1}.thumb.png`,
    dataAiHint: "Cynthia Roselia grass poison",
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '7/244',
  },
  {
    id: 'dri-cynthias-roserade-008',
    name: "Cynthia's Roserade",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Cynthia's Roserade")}.DRI.8.${baseUniqueId + 8 - 1}.thumb.png`,
    dataAiHint: "Cynthia Roserade bouquet pokemon",
    rarity: 'Holo Rare',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '8/244',
  },
  {
    id: 'dri-mow-rotom-009',
    name: 'Mow Rotom',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mow Rotom")}.DRI.9.${baseUniqueId + 9 - 1}.thumb.png`,
    dataAiHint: 'Mow Rotom plasma grass',
    rarity: 'Holo Rare',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '9/244',
  },
  {
    id: 'dri-shaymin-010',
    name: 'Shaymin',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Shaymin")}.DRI.10.${baseUniqueId + 10 - 1}.thumb.png`,
    dataAiHint: 'Shaymin gratitude pokemon',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '10/244',
  },
  {
    id: 'dri-rowlet-011',
    name: 'Rowlet',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Rowlet")}.DRI.11.${baseUniqueId + 11 - 1}.thumb.png`,
    dataAiHint: 'Rowlet grass quill pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '11/244',
  },
  {
    id: 'dri-dartrix-012',
    name: 'Dartrix',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dartrix")}.DRI.12.${baseUniqueId + 12 - 1}.thumb.png`,
    dataAiHint: 'Dartrix blade quill pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '12/244',
  },
  {
    id: 'dri-decidueye-013',
    name: 'Decidueye',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Decidueye")}.DRI.13.${baseUniqueId + 13 - 1}.thumb.png`,
    dataAiHint: 'Decidueye arrow quill pokemon',
    rarity: 'Holo Rare',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '13/244',
  },
  {
    id: 'dri-fomantis-014',
    name: 'Fomantis',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Fomantis")}.DRI.14.${baseUniqueId + 14 - 1}.thumb.png`,
    dataAiHint: 'Fomantis sickle grass pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '14/244',
  },
  {
    id: 'dri-lurantis-015',
    name: 'Lurantis',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Lurantis")}.DRI.15.${baseUniqueId + 15 - 1}.thumb.png`,
    dataAiHint: 'Lurantis bloom sickle pokemon',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '15/244',
  },
  {
    id: 'dri-team-rockets-blipbug-016',
    name: "Team Rocket's Blipbug",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Team Rockets Blipbug")}.DRI.16.${baseUniqueId + 16 - 1}.thumb.png`,
    dataAiHint: "Team Rocket Blipbug larva",
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '16/244',
  },
  {
    id: 'dri-applin-017',
    name: 'Applin',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Applin")}.DRI.17.${baseUniqueId + 17 - 1}.thumb.png`,
    dataAiHint: 'Applin apple core pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '17/244',
  },
  {
    id: 'dri-dipplin-018',
    name: 'Dipplin',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dipplin")}.DRI.18.${baseUniqueId + 18 - 1}.thumb.png`,
    dataAiHint: 'Dipplin candy apple pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '18/244',
  },
  {
    id: 'dri-hydrapple-019',
    name: 'Hydrapple',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Hydrapple")}.DRI.19.${baseUniqueId + 19 - 1}.thumb.png`,
    dataAiHint: 'Hydrapple apple hydra pokemon',
    rarity: 'Holo Rare',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '19/244',
  },
  {
    id: 'dri-team-rockets-tarountula-020',
    name: "Team Rocket's Tarountula",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Team Rockets Tarountula")}.DRI.20.${baseUniqueId + 20 - 1}.thumb.png`,
    dataAiHint: "Team Rocket Tarountula string ball",
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '20/244',
  },
  {
    id: 'dri-team-rockets-spidops-021',
    name: "Team Rocket's Spidops",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Team Rockets Spidops")}.DRI.21.${baseUniqueId + 21 - 1}.thumb.png`,
    dataAiHint: "Team Rocket Spidops trap pokemon",
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '21/244',
  },
  {
    id: 'dri-smoliv-022',
    name: 'Smoliv',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Smoliv")}.DRI.22.${baseUniqueId + 22 - 1}.thumb.png`,
    dataAiHint: 'Smoliv olive pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '22/244',
  },
  {
    id: 'dri-dolliv-023',
    name: 'Dolliv',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dolliv")}.DRI.23.${baseUniqueId + 23 - 1}.thumb.png`,
    dataAiHint: 'Dolliv olive pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '23/244',
  },
  {
    id: 'dri-arboliva-ex-024',
    name: 'Arboliva ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Arboliva ex")}.DRI.24.${baseUniqueId + 24 - 1}.thumb.png`,
    dataAiHint: 'Arboliva ex olive pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '24/244',
  },
  {
    id: 'dri-rellor-025',
    name: 'Rellor',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Rellor")}.DRI.25.${baseUniqueId + 25 - 1}.thumb.png`,
    dataAiHint: 'Rellor rolling pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '25/244',
  },
  {
    id: 'dri-rabsca-ex-026',
    name: 'Rabsca ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Rabsca ex")}.DRI.26.${baseUniqueId + 26 - 1}.thumb.png`,
    dataAiHint: 'Rabsca ex rolling pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '26/244',
  },
  {
    id: 'dri-teal-mask-ogerpon-027',
    name: 'Teal Mask Ogerpon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Teal Mask Ogerpon")}.DRI.27.${baseUniqueId + 27 - 1}.thumb.png`,
    dataAiHint: 'Teal Mask Ogerpon mask pokemon',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '27/244',
  },
  {
    id: 'dri-growlithe-028',
    name: 'Growlithe',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Growlithe")}.DRI.28.${baseUniqueId + 28 - 1}.thumb.png`,
    dataAiHint: 'Growlithe puppy pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '28/244',
  },
  {
    id: 'dri-arcanine-029',
    name: 'Arcanine',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Arcanine")}.DRI.29.${baseUniqueId + 29 - 1}.thumb.png`,
    dataAiHint: 'Arcanine legendary pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '29/244',
  },
  {
    id: 'dri-ponyta-030',
    name: 'Ponyta',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ponyta")}.DRI.30.${baseUniqueId + 30 - 1}.thumb.png`,
    dataAiHint: 'Ponyta fire horse pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '30/244',
  },
  {
    id: 'dri-rapidash-031',
    name: 'Rapidash',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Rapidash")}.DRI.31.${baseUniqueId + 31 - 1}.thumb.png`,
    dataAiHint: 'Rapidash fire horse pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '31/244',
  },
  {
    id: 'dri-team-rockets-moltres-ex-032',
    name: "Team Rocket's Moltres ex",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Team Rockets Moltres ex")}.DRI.32.${baseUniqueId + 32 - 1}.thumb.png`,
    dataAiHint: "Team Rocket Moltres ex flame",
    rarity: 'Holo Rare', // ex
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '32/244',
  },
  {
    id: 'dri-ethans-cyndaquil-033',
    name: "Ethan's Cyndaquil",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ethan's Cyndaquil")}.DRI.33.${baseUniqueId + 33 - 1}.thumb.png`,
    dataAiHint: "Ethan Cyndaquil fire mouse",
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '33/244',
  },
  {
    id: 'dri-ethans-quilava-034',
    name: "Ethan's Quilava",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ethan's Quilava")}.DRI.34.${baseUniqueId + 34 - 1}.thumb.png`,
    dataAiHint: "Ethan Quilava volcano pokemon",
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '34/244',
  },
  {
    id: 'dri-ethans-typhlosion-035',
    name: "Ethan's Typhlosion",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ethan's Typhlosion")}.DRI.35.${baseUniqueId + 35 - 1}.thumb.png`,
    dataAiHint: "Ethan Typhlosion volcano pokemon",
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '35/244',
  },
  {
    id: 'dri-slugma-036',
    name: 'Slugma',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Slugma")}.DRI.36.${baseUniqueId + 36 - 1}.thumb.png`,
    dataAiHint: 'Slugma lava pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '36/244',
  },
  {
    id: 'dri-ethans-magcargo-037',
    name: "Ethan's Magcargo",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ethan's Magcargo")}.DRI.37.${baseUniqueId + 37 - 1}.thumb.png`,
    dataAiHint: "Ethan Magcargo lava pokemon",
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '37/244',
  },
  {
    id: 'dri-hearthflame-mask-ogerpon-038',
    name: 'Hearthflame Mask Ogerpon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Hearthflame Mask Ogerpon")}.DRI.38.${baseUniqueId + 38 - 1}.thumb.png`,
    dataAiHint: 'Hearthflame Mask Ogerpon fire',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '38/244',
  },
  {
    id: 'dri-magby-039',
    name: 'Magby',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Magby")}.DRI.39.${baseUniqueId + 39 - 1}.thumb.png`,
    dataAiHint: 'Magby live coal pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '39/244',
  },
  {
    id: 'dri-torkoal-040',
    name: 'Torkoal',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Torkoal")}.DRI.40.${baseUniqueId + 40 - 1}.thumb.png`,
    dataAiHint: 'Torkoal coal pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '40/244',
  },
  {
    id: 'dri-heat-rotom-041',
    name: 'Heat Rotom',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Heat Rotom")}.DRI.41.${baseUniqueId + 41 - 1}.thumb.png`,
    dataAiHint: 'Heat Rotom plasma fire',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '41/244',
  },
  {
    id: 'dri-victini-042',
    name: 'Victini',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Victini")}.DRI.42.${baseUniqueId + 42 - 1}.thumb.png`,
    dataAiHint: 'Victini victory pokemon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '42/244',
  },
  {
    id: 'dri-litwick-043',
    name: 'Litwick',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Litwick")}.DRI.43.${baseUniqueId + 43 - 1}.thumb.png`,
    dataAiHint: 'Litwick candle pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '43/244',
  },
  {
    id: 'dri-lampent-044',
    name: 'Lampent',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Lampent")}.DRI.44.${baseUniqueId + 44 - 1}.thumb.png`,
    dataAiHint: 'Lampent lamp pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '44/244',
  },
  {
    id: 'dri-chandelure-045',
    name: 'Chandelure',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Chandelure")}.DRI.45.${baseUniqueId + 45 - 1}.thumb.png`,
    dataAiHint: 'Chandelure luring pokemon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '45/244',
  },
  {
    id: 'dri-volcarona-046',
    name: 'Volcarona',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Volcarona")}.DRI.46.${baseUniqueId + 46 - 1}.thumb.png`,
    dataAiHint: 'Volcarona sun pokemon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '46/244',
  },
  {
    id: 'dri-fletchinder-047',
    name: 'Fletchinder',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Fletchinder")}.DRI.47.${baseUniqueId + 47 - 1}.thumb.png`,
    dataAiHint: 'Fletchinder ember pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '47/244',
  },
  {
    id: 'dri-talonflame-048',
    name: 'Talonflame',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Talonflame")}.DRI.48.${baseUniqueId + 48 - 1}.thumb.png`,
    dataAiHint: 'Talonflame scorching pokemon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '48/244',
  },
  {
    id: 'dri-litten-049',
    name: 'Litten',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Litten")}.DRI.49.${baseUniqueId + 49 - 1}.thumb.png`,
    dataAiHint: 'Litten fire cat pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '49/244',
  },
  {
    id: 'dri-torracat-050',
    name: 'Torracat',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Torracat")}.DRI.50.${baseUniqueId + 50 - 1}.thumb.png`,
    dataAiHint: 'Torracat fire cat pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '50/244',
  },
  {
    id: 'dri-incineroar-ex-051',
    name: 'Incineroar ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Incineroar ex")}.DRI.51.${baseUniqueId + 51 - 1}.thumb.png`,
    dataAiHint: 'Incineroar ex heel pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '51/244',
  },
  {
    id: 'dri-charcadet-052',
    name: 'Charcadet',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Charcadet")}.DRI.52.${baseUniqueId + 52 - 1}.thumb.png`,
    dataAiHint: 'Charcadet fire child pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '52/244',
  },
  {
    id: 'dri-armarouge-ex-053',
    name: 'Armarouge ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Armarouge ex")}.DRI.53.${baseUniqueId + 53 - 1}.thumb.png`,
    dataAiHint: 'Armarouge ex fire warrior',
    rarity: 'Holo Rare', // ex
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '53/244',
  },
  {
    id: 'dri-chi-yu-ex-054',
    name: 'Chi-Yu ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Chi-Yu ex")}.DRI.54.${baseUniqueId + 54 - 1}.thumb.png`,
    dataAiHint: 'Chi-Yu ex ruinous pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '54/244',
  },
  {
    id: 'dri-iron-moth-055',
    name: 'Iron Moth',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Iron Moth")}.DRI.55.${baseUniqueId + 55 - 1}.thumb.png`,
    dataAiHint: 'Iron Moth paradox pokemon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '55/244',
  },
  {
    id: 'dri-silver-feraligatr-056',
    name: "Silver's Feraligatr",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Silver's Feraligatr")}.DRI.56.${baseUniqueId + 56 - 1}.thumb.png`,
    dataAiHint: "Silver Feraligatr big jaw",
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '56/244',
  },
  {
    id: 'dri-suicune-057',
    name: 'Suicune',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Suicune")}.DRI.57.${baseUniqueId + 57 - 1}.thumb.png`,
    dataAiHint: 'Suicune aurora pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '57/244',
  },
  {
    id: 'dri-wailmer-058',
    name: 'Wailmer',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Wailmer")}.DRI.58.${baseUniqueId + 58 - 1}.thumb.png`,
    dataAiHint: 'Wailmer ball whale pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '58/244',
  },
  {
    id: 'dri-wash-rotom-059',
    name: 'Wash Rotom',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Wash Rotom")}.DRI.59.${baseUniqueId + 59 - 1}.thumb.png`,
    dataAiHint: 'Wash Rotom plasma water',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '59/244',
  },
  {
    id: 'dri-oshawott-060',
    name: 'Oshawott',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Oshawott")}.DRI.60.${baseUniqueId + 60 - 1}.thumb.png`,
    dataAiHint: 'Oshawott sea otter pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '60/244',
  },
  {
    id: 'dri-dewott-061',
    name: 'Dewott',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dewott")}.DRI.61.${baseUniqueId + 61 - 1}.thumb.png`,
    dataAiHint: 'Dewott discipline pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '61/244',
  },
  {
    id: 'dri-samurott-062',
    name: 'Samurott',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Samurott")}.DRI.62.${baseUniqueId + 62 - 1}.thumb.png`,
    dataAiHint: 'Samurott formidable pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '62/244',
  },
  {
    id: 'dri-tympole-063',
    name: 'Tympole',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Tympole")}.DRI.63.${baseUniqueId + 63 - 1}.thumb.png`,
    dataAiHint: 'Tympole tadpole pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '63/244',
  },
  {
    id: 'dri-palpitoad-064',
    name: 'Palpitoad',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Palpitoad")}.DRI.64.${baseUniqueId + 64 - 1}.thumb.png`,
    dataAiHint: 'Palpitoad vibration pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '64/244',
  },
  {
    id: 'dri-seismitoad-065',
    name: 'Seismitoad',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Seismitoad")}.DRI.65.${baseUniqueId + 65 - 1}.thumb.png`,
    dataAiHint: 'Seismitoad vibration pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '65/244',
  },
  {
    id: 'dri-keldeo-066',
    name: 'Keldeo',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Keldeo")}.DRI.66.${baseUniqueId + 66 - 1}.thumb.png`,
    dataAiHint: 'Keldeo colt pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '66/244',
  },
  {
    id: 'dri-froakie-067',
    name: 'Froakie',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Froakie")}.DRI.67.${baseUniqueId + 67 - 1}.thumb.png`,
    dataAiHint: 'Froakie bubble frog pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '67/244',
  },
  {
    id: 'dri-frogadier-068',
    name: 'Frogadier',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Frogadier")}.DRI.68.${baseUniqueId + 68 - 1}.thumb.png`,
    dataAiHint: 'Frogadier bubble frog pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '68/244',
  },
  {
    id: 'dri-greninja-ex-069',
    name: 'Greninja ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Greninja ex")}.DRI.69.${baseUniqueId + 69 - 1}.thumb.png`,
    dataAiHint: 'Greninja ex ninja pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '69/244',
  },
  {
    id: 'dri-clauncher-070',
    name: 'Clauncher',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Clauncher")}.DRI.70.${baseUniqueId + 70 - 1}.thumb.png`,
    dataAiHint: 'Clauncher water gun pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '70/244',
  },
  {
    id: 'dri-clawitzer-071',
    name: 'Clawitzer',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Clawitzer")}.DRI.71.${baseUniqueId + 71 - 1}.thumb.png`,
    dataAiHint: 'Clawitzer howitzer pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '71/244',
  },
  {
    id: 'dri-wellspring-mask-ogerpon-072',
    name: 'Wellspring Mask Ogerpon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Wellspring Mask Ogerpon")}.DRI.72.${baseUniqueId + 72 - 1}.thumb.png`,
    dataAiHint: 'Wellspring Mask Ogerpon water',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '72/244',
  },
  {
    id: 'dri-bruxish-073',
    name: 'Bruxish',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Bruxish")}.DRI.73.${baseUniqueId + 73 - 1}.thumb.png`,
    dataAiHint: 'Bruxish gnash teeth pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '73/244',
  },
  {
    id: 'dri-walking-wake-ex-074',
    name: 'Walking Wake ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Walking Wake ex")}.DRI.74.${baseUniqueId + 74 - 1}.thumb.png`,
    dataAiHint: 'Walking Wake ex paradox pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '74/244',
  },
  {
    id: 'dri-iron-bundle-075',
    name: 'Iron Bundle',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Iron Bundle")}.DRI.75.${baseUniqueId + 75 - 1}.thumb.png`,
    dataAiHint: 'Iron Bundle paradox pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '75/244',
  },
  {
    id: 'dri-pikachu-076',
    name: 'Pikachu',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Pikachu")}.DRI.76.${baseUniqueId + 76 - 1}.thumb.png`,
    dataAiHint: 'Pikachu mouse pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '76/244',
  },
  {
    id: 'dri-raichu-077',
    name: 'Raichu',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Raichu")}.DRI.77.${baseUniqueId + 77 - 1}.thumb.png`,
    dataAiHint: 'Raichu mouse pokemon',
    rarity: 'Uncommon',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '77/244',
  },
  {
    id: 'dri-team-rockets-zapdos-ex-078',
    name: "Team Rocket's Zapdos ex",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Team Rockets Zapdos ex")}.DRI.78.${baseUniqueId + 78 - 1}.thumb.png`,
    dataAiHint: "Team Rocket Zapdos ex electric",
    rarity: 'Holo Rare', // ex
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '78/244',
  },
  {
    id: 'dri-mareep-079',
    name: 'Mareep',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mareep")}.DRI.79.${baseUniqueId + 79 - 1}.thumb.png`,
    dataAiHint: 'Mareep wool pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '79/244',
  },
  {
    id: 'dri-flaaffy-080',
    name: 'Flaaffy',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Flaaffy")}.DRI.80.${baseUniqueId + 80 - 1}.thumb.png`,
    dataAiHint: 'Flaaffy wool pokemon',
    rarity: 'Uncommon',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '80/244',
  },
  {
    id: 'dri-ampharos-081',
    name: 'Ampharos',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ampharos")}.DRI.81.${baseUniqueId + 81 - 1}.thumb.png`,
    dataAiHint: 'Ampharos light pokemon',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '81/244',
  },
  {
    id: 'dri-raikou-082',
    name: 'Raikou',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Raikou")}.DRI.82.${baseUniqueId + 82 - 1}.thumb.png`,
    dataAiHint: 'Raikou thunder pokemon',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '82/244',
  },
  {
    id: 'dri-electrike-083',
    name: 'Electrike',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Electrike")}.DRI.83.${baseUniqueId + 83 - 1}.thumb.png`,
    dataAiHint: 'Electrike lightning pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '83/244',
  },
  {
    id: 'dri-manectric-084',
    name: 'Manectric',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Manectric")}.DRI.84.${baseUniqueId + 84 - 1}.thumb.png`,
    dataAiHint: 'Manectric discharge pokemon',
    rarity: 'Uncommon',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '84/244',
  },
  {
    id: 'dri-shinx-085',
    name: 'Shinx',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Shinx")}.DRI.85.${baseUniqueId + 85 - 1}.thumb.png`,
    dataAiHint: 'Shinx flash pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '85/244',
  },
  {
    id: 'dri-luxio-086',
    name: 'Luxio',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Luxio")}.DRI.86.${baseUniqueId + 86 - 1}.thumb.png`,
    dataAiHint: 'Luxio spark pokemon',
    rarity: 'Uncommon',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '86/244',
  },
  {
    id: 'dri-luxray-087',
    name: 'Luxray',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Luxray")}.DRI.87.${baseUniqueId + 87 - 1}.thumb.png`,
    dataAiHint: 'Luxray gleam eyes pokemon',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '87/244',
  },
  {
    id: 'dri-frost-rotom-088',
    name: 'Frost Rotom',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Frost Rotom")}.DRI.88.${baseUniqueId + 88 - 1}.thumb.png`,
    dataAiHint: 'Frost Rotom plasma ice',
    rarity: 'Holo Rare',
    type: 'Lightning', // Electric/Ice
    series: 'Destined Rivals',
    pokedexNumber: '88/244',
  },
  {
    id: 'dri-blitzle-089',
    name: 'Blitzle',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Blitzle")}.DRI.89.${baseUniqueId + 89 - 1}.thumb.png`,
    dataAiHint: 'Blitzle electrike pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '89/244',
  },
  {
    id: 'dri-zebstrika-090',
    name: 'Zebstrika',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Zebstrika")}.DRI.90.${baseUniqueId + 90 - 1}.thumb.png`,
    dataAiHint: 'Zebstrika thunderbolt pokemon',
    rarity: 'Uncommon',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '90/244',
  },
  {
    id: 'dri-helioptile-091',
    name: 'Helioptile',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Helioptile")}.DRI.91.${baseUniqueId + 91 - 1}.thumb.png`,
    dataAiHint: 'Helioptile generator pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '91/244',
  },
  {
    id: 'dri-heliolisk-092',
    name: 'Heliolisk',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Heliolisk")}.DRI.92.${baseUniqueId + 92 - 1}.thumb.png`,
    dataAiHint: 'Heliolisk generator pokemon',
    rarity: 'Uncommon',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '92/244',
  },
  {
    id: 'dri-vikavolt-093',
    name: 'Vikavolt',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Vikavolt")}.DRI.93.${baseUniqueId + 93 - 1}.thumb.png`,
    dataAiHint: 'Vikavolt stag beetle pokemon',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '93/244',
  },
  {
    id: 'dri-zeraora-094',
    name: 'Zeraora',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Zeraora")}.DRI.94.${baseUniqueId + 94 - 1}.thumb.png`,
    dataAiHint: 'Zeraora thunderclap pokemon',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '94/244',
  },
  {
    id: 'dri-pawmi-095',
    name: 'Pawmi',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Pawmi")}.DRI.95.${baseUniqueId + 95 - 1}.thumb.png`,
    dataAiHint: 'Pawmi mouse pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '95/244',
  },
  {
    id: 'dri-pawmo-096',
    name: 'Pawmo',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Pawmo")}.DRI.96.${baseUniqueId + 96 - 1}.thumb.png`,
    dataAiHint: 'Pawmo mouse pokemon',
    rarity: 'Uncommon',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '96/244',
  },
  {
    id: 'dri-pawmot-ex-097',
    name: 'Pawmot ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Pawmot ex")}.DRI.97.${baseUniqueId + 97 - 1}.thumb.png`,
    dataAiHint: 'Pawmot ex hands-on pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '97/244',
  },
  {
    id: 'dri-iron-thorns-ex-098',
    name: 'Iron Thorns ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Iron Thorns ex")}.DRI.98.${baseUniqueId + 98 - 1}.thumb.png`,
    dataAiHint: 'Iron Thorns ex paradox pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '98/244',
  },
  {
    id: 'dri-miraidon-ex-099',
    name: 'Miraidon ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Miraidon ex")}.DRI.99.${baseUniqueId + 99 - 1}.thumb.png`,
    dataAiHint: 'Miraidon ex iron serpent',
    rarity: 'Holo Rare', // ex
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '99/244',
  },
  {
    id: 'dri-clefairy-100',
    name: 'Clefairy',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Clefairy")}.DRI.100.${baseUniqueId + 100 - 1}.thumb.png`,
    dataAiHint: 'Clefairy fairy pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '100/244',
  },
  {
    id: 'dri-clefable-101',
    name: 'Clefable',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Clefable")}.DRI.101.${baseUniqueId + 101 - 1}.thumb.png`,
    dataAiHint: 'Clefable fairy pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '101/244',
  },
  {
    id: 'dri-team-rockets-mewtwo-ex-102',
    name: "Team Rocket's Mewtwo ex",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Team Rockets Mewtwo ex")}.DRI.102.${baseUniqueId + 102 - 1}.thumb.png`,
    dataAiHint: "Team Rocket Mewtwo ex genetic",
    rarity: 'Holo Rare', // ex
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '102/244',
  },
  {
    id: 'dri-espeon-103',
    name: 'Espeon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Espeon")}.DRI.103.${baseUniqueId + 103 - 1}.thumb.png`,
    dataAiHint: 'Espeon sun pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '103/244',
  },
  {
    id: 'dri-misdreavus-104',
    name: 'Misdreavus',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Misdreavus")}.DRI.104.${baseUniqueId + 104 - 1}.thumb.png`,
    dataAiHint: 'Misdreavus screech pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '104/244',
  },
  {
    id: 'dri-mismagius-105',
    name: 'Mismagius',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mismagius")}.DRI.105.${baseUniqueId + 105 - 1}.thumb.png`,
    dataAiHint: 'Mismagius magical pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '105/244',
  },
  {
    id: 'dri-chingling-106',
    name: 'Chingling',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Chingling")}.DRI.106.${baseUniqueId + 106 - 1}.thumb.png`,
    dataAiHint: 'Chingling bell pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '106/244',
  },
  {
    id: 'dri-chimecho-107',
    name: 'Chimecho',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Chimecho")}.DRI.107.${baseUniqueId + 107 - 1}.thumb.png`,
    dataAiHint: 'Chimecho wind chime pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '107/244',
  },
  {
    id: 'dri-fan-rotom-108',
    name: 'Fan Rotom',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Fan Rotom")}.DRI.108.${baseUniqueId + 108 - 1}.thumb.png`,
    dataAiHint: 'Fan Rotom plasma flying',
    rarity: 'Holo Rare',
    type: 'Psychic', // Electric/Flying
    series: 'Destined Rivals',
    pokedexNumber: '108/244',
  },
  {
    id: 'dri-uxie-109',
    name: 'Uxie',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Uxie")}.DRI.109.${baseUniqueId + 109 - 1}.thumb.png`,
    dataAiHint: 'Uxie knowledge pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '109/244',
  },
  {
    id: 'dri-mesprit-110',
    name: 'Mesprit',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mesprit")}.DRI.110.${baseUniqueId + 110 - 1}.thumb.png`,
    dataAiHint: 'Mesprit emotion pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '110/244',
  },
  {
    id: 'dri-azelf-111',
    name: 'Azelf',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Azelf")}.DRI.111.${baseUniqueId + 111 - 1}.thumb.png`,
    dataAiHint: 'Azelf willpower pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '111/244',
  },
  {
    id: 'dri-cresselia-112',
    name: 'Cresselia',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Cresselia")}.DRI.112.${baseUniqueId + 112 - 1}.thumb.png`,
    dataAiHint: 'Cresselia lunar pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '112/244',
  },
  {
    id: 'dri-munna-113',
    name: 'Munna',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Munna")}.DRI.113.${baseUniqueId + 113 - 1}.thumb.png`,
    dataAiHint: 'Munna dream eater pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '113/244',
  },
  {
    id: 'dri-musharna-114',
    name: 'Musharna',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Musharna")}.DRI.114.${baseUniqueId + 114 - 1}.thumb.png`,
    dataAiHint: 'Musharna drowsing pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '114/244',
  },
  {
    id: 'dri-elgyem-115',
    name: 'Elgyem',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Elgyem")}.DRI.115.${baseUniqueId + 115 - 1}.thumb.png`,
    dataAiHint: 'Elgyem cerebral pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '115/244',
  },
  {
    id: 'dri-beheeyem-116',
    name: 'Beheeyem',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Beheeyem")}.DRI.116.${baseUniqueId + 116 - 1}.thumb.png`,
    dataAiHint: 'Beheeyem cerebral pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '116/244',
  },
  {
    id: 'dri-phantump-117',
    name: 'Phantump',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Phantump")}.DRI.117.${baseUniqueId + 117 - 1}.thumb.png`,
    dataAiHint: 'Phantump stump pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '117/244',
  },
  {
    id: 'dri-trevenant-118',
    name: 'Trevenant',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Trevenant")}.DRI.118.${baseUniqueId + 118 - 1}.thumb.png`,
    dataAiHint: 'Trevenant elder tree pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '118/244',
  },
  {
    id: 'dri-gardevoir-ex-119',
    name: 'Gardevoir ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Gardevoir ex")}.DRI.119.${baseUniqueId + 119 - 1}.thumb.png`,
    dataAiHint: 'Gardevoir ex embrace pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '119/244',
  },
  {
    id: 'dri-mimikyu-120',
    name: 'Mimikyu',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mimikyu")}.DRI.120.${baseUniqueId + 120 - 1}.thumb.png`,
    dataAiHint: 'Mimikyu disguise pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '120/244',
  },
  {
    id: 'dri-flutter-mane-121',
    name: 'Flutter Mane',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Flutter Mane")}.DRI.121.${baseUniqueId + 121 - 1}.thumb.png`,
    dataAiHint: 'Flutter Mane paradox pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '121/244',
  },
  {
    id: 'dri-scream-tail-122',
    name: 'Scream Tail',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Scream Tail")}.DRI.122.${baseUniqueId + 122 - 1}.thumb.png`,
    dataAiHint: 'Scream Tail paradox pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '122/244',
  },
  {
    id: 'dri-mankey-123',
    name: 'Mankey',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mankey")}.DRI.123.${baseUniqueId + 123 - 1}.thumb.png`,
    dataAiHint: 'Mankey pig monkey pokemon',
    rarity: 'Common',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '123/244',
  },
  {
    id: 'dri-primeape-124',
    name: 'Primeape',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Primeape")}.DRI.124.${baseUniqueId + 124 - 1}.thumb.png`,
    dataAiHint: 'Primeape pig monkey pokemon',
    rarity: 'Uncommon',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '124/244',
  },
  {
    id: 'dri-annihilape-ex-125',
    name: 'Annihilape ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Annihilape ex")}.DRI.125.${baseUniqueId + 125 - 1}.thumb.png`,
    dataAiHint: 'Annihilape ex rage monkey',
    rarity: 'Holo Rare', // ex
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '125/244',
  },
  {
    id: 'dri-hitmontop-126',
    name: 'Hitmontop',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Hitmontop")}.DRI.126.${baseUniqueId + 126 - 1}.thumb.png`,
    dataAiHint: 'Hitmontop handstand pokemon',
    rarity: 'Uncommon',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '126/244',
  },
  {
    id: 'dri-makuhita-127',
    name: 'Makuhita',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Makuhita")}.DRI.127.${baseUniqueId + 127 - 1}.thumb.png`,
    dataAiHint: 'Makuhita guts pokemon',
    rarity: 'Common',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '127/244',
  },
  {
    id: 'dri-hariyama-128',
    name: 'Hariyama',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Hariyama")}.DRI.128.${baseUniqueId + 128 - 1}.thumb.png`,
    dataAiHint: 'Hariyama arm thrust pokemon',
    rarity: 'Uncommon',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '128/244',
  },
  {
    id: 'dri-lucario-129',
    name: 'Lucario',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Lucario")}.DRI.129.${baseUniqueId + 129 - 1}.thumb.png`,
    dataAiHint: 'Lucario aura pokemon',
    rarity: 'Holo Rare',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '129/244',
  },
  {
    id: 'dri-hawlucha-130',
    name: 'Hawlucha',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Hawlucha")}.DRI.130.${baseUniqueId + 130 - 1}.thumb.png`,
    dataAiHint: 'Hawlucha wrestling pokemon',
    rarity: 'Uncommon',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '130/244',
  },
  {
    id: 'dri-passimian-131',
    name: 'Passimian',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Passimian")}.DRI.131.${baseUniqueId + 131 - 1}.thumb.png`,
    dataAiHint: 'Passimian teamwork pokemon',
    rarity: 'Uncommon',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '131/244',
  },
  {
    id: 'dri-falinks-132',
    name: 'Falinks',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Falinks")}.DRI.132.${baseUniqueId + 132 - 1}.thumb.png`,
    dataAiHint: 'Falinks formation pokemon',
    rarity: 'Uncommon',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '132/244',
  },
  {
    id: 'dri-great-tusk-ex-133',
    name: 'Great Tusk ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Great Tusk ex")}.DRI.133.${baseUniqueId + 133 - 1}.thumb.png`,
    dataAiHint: 'Great Tusk ex paradox pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '133/244',
  },
  {
    id: 'dri-slither-wing-134',
    name: 'Slither Wing',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Slither Wing")}.DRI.134.${baseUniqueId + 134 - 1}.thumb.png`,
    dataAiHint: 'Slither Wing paradox pokemon',
    rarity: 'Holo Rare',
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '134/244',
  },
  {
    id: 'dri-iron-hands-ex-135',
    name: 'Iron Hands ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Iron Hands ex")}.DRI.135.${baseUniqueId + 135 - 1}.thumb.png`,
    dataAiHint: 'Iron Hands ex paradox pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '135/244',
  },
  {
    id: 'dri-koraidon-ex-136',
    name: 'Koraidon ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Koraidon ex")}.DRI.136.${baseUniqueId + 136 - 1}.thumb.png`,
    dataAiHint: 'Koraidon ex winged king',
    rarity: 'Holo Rare', // ex
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '136/244',
  },
  {
    id: 'dri-okidogi-ex-137',
    name: 'Okidogi ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Okidogi ex")}.DRI.137.${baseUniqueId + 137 - 1}.thumb.png`,
    dataAiHint: 'Okidogi ex retaliator pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '137/244',
  },
  {
    id: 'dri-murkrow-138',
    name: 'Murkrow',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Murkrow")}.DRI.138.${baseUniqueId + 138 - 1}.thumb.png`,
    dataAiHint: 'Murkrow darkness pokemon',
    rarity: 'Common',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '138/244',
  },
  {
    id: 'dri-honchkrow-139',
    name: 'Honchkrow',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Honchkrow")}.DRI.139.${baseUniqueId + 139 - 1}.thumb.png`,
    dataAiHint: 'Honchkrow big boss pokemon',
    rarity: 'Uncommon',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '139/244',
  },
  {
    id: 'dri-sneasel-140',
    name: 'Sneasel',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Sneasel")}.DRI.140.${baseUniqueId + 140 - 1}.thumb.png`,
    dataAiHint: 'Sneasel sharp claw pokemon',
    rarity: 'Common',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '140/244',
  },
  {
    id: 'dri-weavile-141',
    name: 'Weavile',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Weavile")}.DRI.141.${baseUniqueId + 141 - 1}.thumb.png`,
    dataAiHint: 'Weavile sharp claw pokemon',
    rarity: 'Uncommon',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '141/244',
  },
  {
    id: 'dri-umbreon-142',
    name: 'Umbreon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Umbreon")}.DRI.142.${baseUniqueId + 142 - 1}.thumb.png`,
    dataAiHint: 'Umbreon moonlight pokemon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '142/244',
  },
  {
    id: 'dri-absol-143',
    name: 'Absol',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Absol")}.DRI.143.${baseUniqueId + 143 - 1}.thumb.png`,
    dataAiHint: 'Absol disaster pokemon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '143/244',
  },
  {
    id: 'dri-darkrai-144',
    name: 'Darkrai',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Darkrai")}.DRI.144.${baseUniqueId + 144 - 1}.thumb.png`,
    dataAiHint: 'Darkrai pitch-black pokemon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '144/244',
  },
  {
    id: 'dri-purrloin-145',
    name: 'Purrloin',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Purrloin")}.DRI.145.${baseUniqueId + 145 - 1}.thumb.png`,
    dataAiHint: 'Purrloin devious pokemon',
    rarity: 'Common',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '145/244',
  },
  {
    id: 'dri-liepard-146',
    name: 'Liepard',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Liepard")}.DRI.146.${baseUniqueId + 146 - 1}.thumb.png`,
    dataAiHint: 'Liepard cruel pokemon',
    rarity: 'Uncommon',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '146/244',
  },
  {
    id: 'dri-zorua-147',
    name: 'Zorua',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Zorua")}.DRI.147.${baseUniqueId + 147 - 1}.thumb.png`,
    dataAiHint: 'Zorua tricky fox pokemon',
    rarity: 'Common',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '147/244',
  },
  {
    id: 'dri-zoroark-148',
    name: 'Zoroark',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Zoroark")}.DRI.148.${baseUniqueId + 148 - 1}.thumb.png`,
    dataAiHint: 'Zoroark illusion fox pokemon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '148/244',
  },
  {
    id: 'dri-yveltal-149',
    name: 'Yveltal',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Yveltal")}.DRI.149.${baseUniqueId + 149 - 1}.thumb.png`,
    dataAiHint: 'Yveltal destruction pokemon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '149/244',
  },
  {
    id: 'dri-nickit-150',
    name: 'Nickit',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Nickit")}.DRI.150.${baseUniqueId + 150 - 1}.thumb.png`,
    dataAiHint: 'Nickit fox pokemon',
    rarity: 'Common',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '150/244',
  },
  {
    id: 'dri-thievul-151',
    name: 'Thievul',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Thievul")}.DRI.151.${baseUniqueId + 151 - 1}.thumb.png`,
    dataAiHint: 'Thievul fox pokemon',
    rarity: 'Uncommon',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '151/244',
  },
  {
    id: 'dri-obstagoon-152',
    name: 'Obstagoon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Obstagoon")}.DRI.152.${baseUniqueId + 152 - 1}.thumb.png`,
    dataAiHint: 'Obstagoon blocking pokemon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '152/244',
  },
  {
    id: 'dri-ting-lu-ex-153',
    name: 'Ting-Lu ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ting-Lu ex")}.DRI.153.${baseUniqueId + 153 - 1}.thumb.png`,
    dataAiHint: 'Ting-Lu ex ruinous pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '153/244',
  },
  {
    id: 'dri-brute-bonnet-154',
    name: 'Brute Bonnet',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Brute Bonnet")}.DRI.154.${baseUniqueId + 154 - 1}.thumb.png`,
    dataAiHint: 'Brute Bonnet paradox pokemon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '154/244',
  },
  {
    id: 'dri-kingambit-ex-155',
    name: 'Kingambit ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Kingambit ex")}.DRI.155.${baseUniqueId + 155 - 1}.thumb.png`,
    dataAiHint: 'Kingambit ex big blade pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '155/244',
  },
  {
    id: 'dri-munkidori-ex-156',
    name: 'Munkidori ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Munkidori ex")}.DRI.156.${baseUniqueId + 156 - 1}.thumb.png`,
    dataAiHint: 'Munkidori ex retaliator pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '156/244',
  },
  {
    id: 'dri-steelix-157',
    name: 'Steelix',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Steelix")}.DRI.157.${baseUniqueId + 157 - 1}.thumb.png`,
    dataAiHint: 'Steelix iron snake pokemon',
    rarity: 'Holo Rare',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '157/244',
  },
  {
    id: 'dri-skarmory-158',
    name: 'Skarmory',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Skarmory")}.DRI.158.${baseUniqueId + 158 - 1}.thumb.png`,
    dataAiHint: 'Skarmory armor bird pokemon',
    rarity: 'Uncommon',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '158/244',
  },
  {
    id: 'dri-mawile-159',
    name: 'Mawile',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mawile")}.DRI.159.${baseUniqueId + 159 - 1}.thumb.png`,
    dataAiHint: 'Mawile deceiver pokemon',
    rarity: 'Uncommon',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '159/244',
  },
  {
    id: 'dri-beldum-160',
    name: 'Beldum',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Beldum")}.DRI.160.${baseUniqueId + 160 - 1}.thumb.png`,
    dataAiHint: 'Beldum iron ball pokemon',
    rarity: 'Common',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '160/244',
  },
  {
    id: 'dri-metang-161',
    name: 'Metang',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Metang")}.DRI.161.${baseUniqueId + 161 - 1}.thumb.png`,
    dataAiHint: 'Metang iron claw pokemon',
    rarity: 'Uncommon',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '161/244',
  },
  {
    id: 'dri-metagross-162',
    name: 'Metagross',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Metagross")}.DRI.162.${baseUniqueId + 162 - 1}.thumb.png`,
    dataAiHint: 'Metagross iron leg pokemon',
    rarity: 'Holo Rare',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '162/244',
  },
  {
    id: 'dri-shieldon-163',
    name: 'Shieldon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Shieldon")}.DRI.163.${baseUniqueId + 163 - 1}.thumb.png`,
    dataAiHint: 'Shieldon shield pokemon',
    rarity: 'Common',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '163/244',
  },
  {
    id: 'dri-bastiodon-164',
    name: 'Bastiodon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Bastiodon")}.DRI.164.${baseUniqueId + 164 - 1}.thumb.png`,
    dataAiHint: 'Bastiodon shield pokemon',
    rarity: 'Uncommon',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '164/244',
  },
  {
    id: 'dri-dialga-165',
    name: 'Dialga',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dialga")}.DRI.165.${baseUniqueId + 165 - 1}.thumb.png`,
    dataAiHint: 'Dialga temporal pokemon',
    rarity: 'Holo Rare',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '165/244',
  },
  {
    id: 'dri-cobalion-166',
    name: 'Cobalion',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Cobalion")}.DRI.166.${baseUniqueId + 166 - 1}.thumb.png`,
    dataAiHint: 'Cobalion iron will pokemon',
    rarity: 'Holo Rare',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '166/244',
  },
  {
    id: 'dri-aegislash-ex-167',
    name: 'Aegislash ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Aegislash ex")}.DRI.167.${baseUniqueId + 167 - 1}.thumb.png`,
    dataAiHint: 'Aegislash ex royal sword',
    rarity: 'Holo Rare', // ex
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '167/244',
  },
  {
    id: 'dri-alolan-dugtrio-168',
    name: 'Alolan Dugtrio',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Alolan Dugtrio")}.DRI.168.${baseUniqueId + 168 - 1}.thumb.png`,
    dataAiHint: 'Alolan Dugtrio mole pokemon',
    rarity: 'Uncommon',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '168/244',
  },
  {
    id: 'dri-togedemaru-169',
    name: 'Togedemaru',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Togedemaru")}.DRI.169.${baseUniqueId + 169 - 1}.thumb.png`,
    dataAiHint: 'Togedemaru roly-poly pokemon',
    rarity: 'Common',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '169/244',
  },
  {
    id: 'dri-heatran-170',
    name: 'Heatran',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Heatran")}.DRI.170.${baseUniqueId + 170 - 1}.thumb.png`,
    dataAiHint: 'Heatran lava dome pokemon',
    rarity: 'Holo Rare',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '170/244',
  },
  {
    id: 'dri-magearna-171',
    name: 'Magearna',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Magearna")}.DRI.171.${baseUniqueId + 171 - 1}.thumb.png`,
    dataAiHint: 'Magearna artificial pokemon',
    rarity: 'Holo Rare',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '171/244',
  },
  {
    id: 'dri-perrserker-172',
    name: 'Perrserker',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Perrserker")}.DRI.172.${baseUniqueId + 172 - 1}.thumb.png`,
    dataAiHint: 'Perrserker viking pokemon',
    rarity: 'Uncommon',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '172/244',
  },
  {
    id: 'dri-copperajah-ex-173',
    name: 'Copperajah ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Copperajah ex")}.DRI.173.${baseUniqueId + 173 - 1}.thumb.png`,
    dataAiHint: 'Copperajah ex copperderm pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '173/244',
  },
  {
    id: 'dri-iron-treads-ex-174',
    name: 'Iron Treads ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Iron Treads ex")}.DRI.174.${baseUniqueId + 174 - 1}.thumb.png`,
    dataAiHint: 'Iron Treads ex paradox pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '174/244',
  },
  {
    id: 'dri-gimmighoul-175',
    name: 'Gimmighoul',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Gimmighoul")}.DRI.175.${baseUniqueId + 175 - 1}.thumb.png`,
    dataAiHint: 'Gimmighoul coin chest pokemon',
    rarity: 'Common',
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '175/244',
  },
  {
    id: 'dri-gholdengo-ex-176',
    name: 'Gholdengo ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Gholdengo ex")}.DRI.176.${baseUniqueId + 176 - 1}.thumb.png`,
    dataAiHint: 'Gholdengo ex coin entity pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Metal',
    series: 'Destined Rivals',
    pokedexNumber: '176/244',
  },
  {
    id: 'dri-dratini-177',
    name: 'Dratini',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dratini")}.DRI.177.${baseUniqueId + 177 - 1}.thumb.png`,
    dataAiHint: 'Dratini dragon pokemon',
    rarity: 'Common',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '177/244',
  },
  {
    id: 'dri-dragonair-178',
    name: 'Dragonair',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dragonair")}.DRI.178.${baseUniqueId + 178 - 1}.thumb.png`,
    dataAiHint: 'Dragonair dragon pokemon',
    rarity: 'Uncommon',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '178/244',
  },
  {
    id: 'dri-dragonite-179',
    name: 'Dragonite',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dragonite")}.DRI.179.${baseUniqueId + 179 - 1}.thumb.png`,
    dataAiHint: 'Dragonite dragon pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '179/244',
  },
  {
    id: 'dri-salamence-180',
    name: 'Salamence',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Salamence")}.DRI.180.${baseUniqueId + 180 - 1}.thumb.png`,
    dataAiHint: 'Salamence dragon pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '180/244',
  },
  {
    id: 'dri-garchomp-ex-181',
    name: 'Garchomp ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Garchomp ex")}.DRI.181.${baseUniqueId + 181 - 1}.thumb.png`,
    dataAiHint: 'Garchomp ex mach pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '181/244',
  },
  {
    id: 'dri-palkia-182',
    name: 'Palkia',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Palkia")}.DRI.182.${baseUniqueId + 182 - 1}.thumb.png`,
    dataAiHint: 'Palkia spatial pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '182/244',
  },
  {
    id: 'dri-giratina-183',
    name: 'Giratina',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Giratina")}.DRI.183.${baseUniqueId + 183 - 1}.thumb.png`,
    dataAiHint: 'Giratina renegade pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '183/244',
  },
  {
    id: 'dri-axew-184',
    name: 'Axew',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Axew")}.DRI.184.${baseUniqueId + 184 - 1}.thumb.png`,
    dataAiHint: 'Axew tusk pokemon',
    rarity: 'Common',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '184/244',
  },
  {
    id: 'dri-fraxure-185',
    name: 'Fraxure',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Fraxure")}.DRI.185.${baseUniqueId + 185 - 1}.thumb.png`,
    dataAiHint: 'Fraxure axe jaw pokemon',
    rarity: 'Uncommon',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '185/244',
  },
  {
    id: 'dri-haxorus-186',
    name: 'Haxorus',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Haxorus")}.DRI.186.${baseUniqueId + 186 - 1}.thumb.png`,
    dataAiHint: 'Haxorus axe jaw pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '186/244',
  },
  {
    id: 'dri-noivern-187',
    name: 'Noivern',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Noivern")}.DRI.187.${baseUniqueId + 187 - 1}.thumb.png`,
    dataAiHint: 'Noivern sound wave pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '187/244',
  },
  {
    id: 'dri-turtonator-188',
    name: 'Turtonator',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Turtonator")}.DRI.188.${baseUniqueId + 188 - 1}.thumb.png`,
    dataAiHint: 'Turtonator blast turtle pokemon',
    rarity: 'Uncommon',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '188/244',
  },
  {
    id: 'dri-duraludon-189',
    name: 'Duraludon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Duraludon")}.DRI.189.${baseUniqueId + 189 - 1}.thumb.png`,
    dataAiHint: 'Duraludon alloy pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '189/244',
  },
  {
    id: 'dri-baxcalibur-190',
    name: 'Baxcalibur',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Baxcalibur")}.DRI.190.${baseUniqueId + 190 - 1}.thumb.png`,
    dataAiHint: 'Baxcalibur ice dragon pokemon',
    rarity: 'Holo Rare',
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '190/244',
  },
  {
    id: 'dri-sylveon-191',
    name: 'Sylveon',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Sylveon")}.DRI.191.${baseUniqueId + 191 - 1}.thumb.png`,
    dataAiHint: 'Sylveon intertwining pokemon',
    rarity: 'Holo Rare',
    type: 'Fairy',
    series: 'Destined Rivals',
    pokedexNumber: '191/244',
  },
  {
    id: 'dri-ribombee-192',
    name: 'Ribombee',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ribombee")}.DRI.192.${baseUniqueId + 192 - 1}.thumb.png`,
    dataAiHint: 'Ribombee bee fly pokemon',
    rarity: 'Uncommon',
    type: 'Fairy',
    series: 'Destined Rivals',
    pokedexNumber: '192/244',
  },
  {
    id: 'dri-alcremie-193',
    name: 'Alcremie',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Alcremie")}.DRI.193.${baseUniqueId + 193 - 1}.thumb.png`,
    dataAiHint: 'Alcremie cream pokemon',
    rarity: 'Holo Rare',
    type: 'Fairy',
    series: 'Destined Rivals',
    pokedexNumber: '193/244',
  },
  {
    id: 'dri-fidough-194',
    name: 'Fidough',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Fidough")}.DRI.194.${baseUniqueId + 194 - 1}.thumb.png`,
    dataAiHint: 'Fidough puppy pokemon',
    rarity: 'Common',
    type: 'Fairy',
    series: 'Destined Rivals',
    pokedexNumber: '194/244',
  },
  {
    id: 'dri-dachsbun-195',
    name: 'Dachsbun',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dachsbun")}.DRI.195.${baseUniqueId + 195 - 1}.thumb.png`,
    dataAiHint: 'Dachsbun dog pokemon',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Fairy',
    series: 'Destined Rivals',
    pokedexNumber: '195/244',
  },
  {
    id: 'dri-tinkaton-ex-196',
    name: 'Tinkaton ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Tinkaton ex")}.DRI.196.${baseUniqueId + 196 - 1}.thumb.png`,
    dataAiHint: 'Tinkaton ex hammer pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Fairy',
    series: 'Destined Rivals',
    pokedexNumber: '196/244',
  },
  {
    id: 'dri-fezendipiti-ex-197',
    name: 'Fezandipiti ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Fezandipiti ex")}.DRI.197.${baseUniqueId + 197 - 1}.thumb.png`,
    dataAiHint: 'Fezandipiti ex retaliator pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Fairy',
    series: 'Destined Rivals',
    pokedexNumber: '197/244',
  },
  {
    id: 'dri-eevee-198',
    name: 'Eevee',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Eevee")}.DRI.198.${baseUniqueId + 198 - 1}.thumb.png`,
    dataAiHint: 'Eevee evolution pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '198/244',
  },
  {
    id: 'dri-snorlax-199',
    name: 'Snorlax',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Snorlax")}.DRI.199.${baseUniqueId + 199 - 1}.thumb.png`,
    dataAiHint: 'Snorlax sleeping pokemon',
    rarity: 'Holo Rare',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '199/244',
  },
  {
    id: 'dri-blissey-ex-200',
    name: 'Blissey ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Blissey ex")}.DRI.200.${baseUniqueId + 200 - 1}.thumb.png`,
    dataAiHint: 'Blissey ex happiness pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '200/244',
  },
  {
    id: 'dri-pidove-201',
    name: 'Pidove',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Pidove")}.DRI.201.${baseUniqueId + 201 - 1}.thumb.png`,
    dataAiHint: 'Pidove tiny pigeon pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '201/244',
  },
  {
    id: 'dri-tranquill-202',
    name: 'Tranquill',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Tranquill")}.DRI.202.${baseUniqueId + 202 - 1}.thumb.png`,
    dataAiHint: 'Tranquill wild pigeon pokemon',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '202/244',
  },
  {
    id: 'dri-unfezant-203',
    name: 'Unfezant',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Unfezant")}.DRI.203.${baseUniqueId + 203 - 1}.thumb.png`,
    dataAiHint: 'Unfezant proud pokemon',
    rarity: 'Holo Rare',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '203/244',
  },
  {
    id: 'dri-lugia-204',
    name: 'Lugia',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Lugia")}.DRI.204.${baseUniqueId + 204 - 1}.thumb.png`,
    dataAiHint: 'Lugia diving pokemon',
    rarity: 'Holo Rare',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '204/244',
  },
  {
    id: 'dri-slaking-v-205',
    name: 'Slaking V',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Slaking V")}.DRI.205.${baseUniqueId + 205 - 1}.thumb.png`,
    dataAiHint: 'Slaking V lazy pokemon',
    rarity: 'Holo Rare', // V
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '205/244',
  },
  {
    id: 'dri-yungoos-206',
    name: 'Yungoos',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Yungoos")}.DRI.206.${baseUniqueId + 206 - 1}.thumb.png`,
    dataAiHint: 'Yungoos loitering pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '206/244',
  },
  {
    id: 'dri-gumshoos-207',
    name: 'Gumshoos',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Gumshoos")}.DRI.207.${baseUniqueId + 207 - 1}.thumb.png`,
    dataAiHint: 'Gumshoos stakeout pokemon',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '207/244',
  },
  {
    id: 'dri-drampa-208',
    name: 'Drampa',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Drampa")}.DRI.208.${baseUniqueId + 208 - 1}.thumb.png`,
    dataAiHint: 'Drampa placcid dragon',
    rarity: 'Rare',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '208/244',
  },
  {
    id: 'dri-indeedee-209',
    name: 'Indeedee',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Indeedee")}.DRI.209.${baseUniqueId + 209 - 1}.thumb.png`,
    dataAiHint: 'Indeedee emotion pokemon',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '209/244',
  },
  {
    id: 'dri-lechonk-210',
    name: 'Lechonk',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Lechonk")}.DRI.210.${baseUniqueId + 210 - 1}.thumb.png`,
    dataAiHint: 'Lechonk hog pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '210/244',
  },
  {
    id: 'dri-oinkologne-211',
    name: 'Oinkologne',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Oinkologne")}.DRI.211.${baseUniqueId + 211 - 1}.thumb.png`,
    dataAiHint: 'Oinkologne hog pokemon',
    rarity: 'Rare',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '211/244',
  },
  {
    id: 'dri-dudunsparce-212',
    name: 'Dudunsparce',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Dudunsparce")}.DRI.212.${baseUniqueId + 212 - 1}.thumb.png`,
    dataAiHint: 'Dudunsparce land snake',
    rarity: 'Holo Rare', // Illustration Rare
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '212/244',
  },
  {
    id: 'dri-cyclizar-ex-213',
    name: 'Cyclizar ex',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Cyclizar ex")}.DRI.213.${baseUniqueId + 213 - 1}.thumb.png`,
    dataAiHint: 'Cyclizar ex mount pokemon',
    rarity: 'Holo Rare', // ex
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '213/244',
  },
  {
    id: 'dri-arven-214',
    name: 'Arven',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Arven")}.DRI.214.${baseUniqueId + 214 - 1}.thumb.png`,
    dataAiHint: 'Arven supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '214/244',
  },
  {
    id: 'dri-professors-research-sada-215',
    name: "Professor's Research (Professor Sada)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Professors Research Professor Sada")}.DRI.215.${baseUniqueId + 215 - 1}.thumb.png`,
    dataAiHint: 'Professor Sada supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '215/244',
  },
  {
    id: 'dri-professors-research-turo-216',
    name: "Professor's Research (Professor Turo)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Professors Research Professor Turo")}.DRI.216.${baseUniqueId + 216 - 1}.thumb.png`,
    dataAiHint: 'Professor Turo supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '216/244',
  },
  {
    id: 'dri-bosss-orders-giovanni-217',
    name: "Boss's Orders (Giovanni)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Boss Orders Giovanni")}.DRI.217.${baseUniqueId + 217 - 1}.thumb.png`,
    dataAiHint: 'Giovanni supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '217/244',
  },
  {
    id: 'dri-bosss-orders-cyrus-218',
    name: "Boss's Orders (Cyrus)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Boss Orders Cyrus")}.DRI.218.${baseUniqueId + 218 - 1}.thumb.png`,
    dataAiHint: 'Cyrus supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '218/244',
  },
  {
    id: 'dri-bosss-orders-ghetsis-219',
    name: "Boss's Orders (Ghetsis)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Boss Orders Ghetsis")}.DRI.219.${baseUniqueId + 219 - 1}.thumb.png`,
    dataAiHint: 'Ghetsis supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '219/244',
  },
  {
    id: 'dri-bosss-orders-lysandre-220',
    name: "Boss's Orders (Lysandre)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Boss Orders Lysandre")}.DRI.220.${baseUniqueId + 220 - 1}.thumb.png`,
    dataAiHint: 'Lysandre supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '220/244',
  },
  {
    id: 'dri-bosss-orders-guzma-221',
    name: "Boss's Orders (Guzma)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Boss Orders Guzma")}.DRI.221.${baseUniqueId + 221 - 1}.thumb.png`,
    dataAiHint: 'Guzma supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '221/244',
  },
  {
    id: 'dri-bosss-orders-rose-222',
    name: "Boss's Orders (Rose)",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Boss Orders Rose")}.DRI.222.${baseUniqueId + 222 - 1}.thumb.png`,
    dataAiHint: 'Rose supporter',
    rarity: 'Holo Rare',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '222/244',
  },
  {
    id: 'dri-iono-223',
    name: 'Iono',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Iono")}.DRI.223.${baseUniqueId + 223 - 1}.thumb.png`,
    dataAiHint: 'Iono supporter',
    rarity: 'Holo Rare', // Ultra Rare
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '223/244',
  },
  {
    id: 'dri-giacomo-224',
    name: 'Giacomo',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Giacomo")}.DRI.224.${baseUniqueId + 224 - 1}.thumb.png`,
    dataAiHint: 'Giacomo supporter',
    rarity: 'Holo Rare', // Ultra Rare
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '224/244',
  },
  {
    id: 'dri-nemona-225',
    name: 'Nemona',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Nemona")}.DRI.225.${baseUniqueId + 225 - 1}.thumb.png`,
    dataAiHint: 'Nemona supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '225/244',
  },
  {
    id: 'dri-penny-226',
    name: 'Penny',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Penny")}.DRI.226.${baseUniqueId + 226 - 1}.thumb.png`,
    dataAiHint: 'Penny supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '226/244',
  },
  {
    id: 'dri-clive-227',
    name: 'Clive',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Clive")}.DRI.227.${baseUniqueId + 227 - 1}.thumb.png`,
    dataAiHint: 'Clive supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '227/244',
  },
  {
    id: 'dri-mela-228',
    name: 'Mela',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mela")}.DRI.228.${baseUniqueId + 228 - 1}.thumb.png`,
    dataAiHint: 'Mela supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '228/244',
  },
  {
    id: 'dri-atticus-229',
    name: 'Atticus',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Atticus")}.DRI.229.${baseUniqueId + 229 - 1}.thumb.png`,
    dataAiHint: 'Atticus supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '229/244',
  },
  {
    id: 'dri-ortega-230',
    name: 'Ortega',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Ortega")}.DRI.230.${baseUniqueId + 230 - 1}.thumb.png`,
    dataAiHint: 'Ortega supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '230/244',
  },
  {
    id: 'dri-eri-231',
    name: 'Eri',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Eri")}.DRI.231.${baseUniqueId + 231 - 1}.thumb.png`,
    dataAiHint: 'Eri supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '231/244',
  },
  {
    id: 'dri-riley-232',
    name: 'Riley',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Riley")}.DRI.232.${baseUniqueId + 232 - 1}.thumb.png`,
    dataAiHint: 'Riley supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '232/244',
  },
  {
    id: 'dri-cheryl-233',
    name: 'Cheryl',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Cheryl")}.DRI.233.${baseUniqueId + 233 - 1}.thumb.png`,
    dataAiHint: 'Cheryl supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '233/244',
  },
  {
    id: 'dri-mira-234',
    name: 'Mira',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Mira")}.DRI.234.${baseUniqueId + 234 - 1}.thumb.png`,
    dataAiHint: 'Mira supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '234/244',
  },
  {
    id: 'dri-marley-235',
    name: 'Marley',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Marley")}.DRI.235.${baseUniqueId + 235 - 1}.thumb.png`,
    dataAiHint: 'Marley supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '235/244',
  },
  {
    id: 'dri-buck-236',
    name: 'Buck',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Buck")}.DRI.236.${baseUniqueId + 236 - 1}.thumb.png`,
    dataAiHint: 'Buck supporter',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '236/244',
  },
  {
    id: 'dri-silver-237',
    name: 'Silver',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Silver")}.DRI.237.${baseUniqueId + 237 - 1}.thumb.png`,
    dataAiHint: 'Silver trainer rival',
    rarity: 'Holo Rare', // Special Illustration Rare
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '237/244',
  },
  {
    id: 'dri-blue-238',
    name: 'Blue',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Blue")}.DRI.238.${baseUniqueId + 238 - 1}.thumb.png`,
    dataAiHint: 'Blue trainer rival',
    rarity: 'Holo Rare', // Special Illustration Rare
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '238/244',
  },
  {
    id: 'dri-red-239',
    name: 'Red',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Red")}.DRI.239.${baseUniqueId + 239 - 1}.thumb.png`,
    dataAiHint: 'Red trainer champion',
    rarity: 'Holo Rare', // Special Illustration Rare
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '239/244',
  },
  {
    id: 'dri-choice-belt-240',
    name: 'Choice Belt',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Choice Belt")}.DRI.240.${baseUniqueId + 240 - 1}.thumb.png`,
    dataAiHint: 'Choice Belt item',
    rarity: 'Holo Rare', // Hyper Rare (Gold)
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '240/244',
  },
  {
    id: 'dri-forest-seal-stone-241',
    name: 'Forest Seal Stone',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Forest Seal Stone")}.DRI.241.${baseUniqueId + 241 - 1}.thumb.png`,
    dataAiHint: 'Forest Seal Stone item',
    rarity: 'Holo Rare', // Hyper Rare (Gold)
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '241/244',
  },
  {
    id: 'dri-team-rockets-crobat-ex-242',
    name: "Team Rocket's Crobat ex",
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Team Rockets Crobat ex")}.DRI.242.${baseUniqueId + 242 - 1}.thumb.png`,
    dataAiHint: "Team Rocket Crobat ex bat",
    rarity: 'Holo Rare', // Special Illustration Rare
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '242/244',
  },
  {
    id: 'dri-jamming-tower-243',
    name: 'Jamming Tower',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Jamming Tower")}.DRI.243.${baseUniqueId + 243 - 1}.thumb.png`,
    dataAiHint: 'Jamming Tower stadium trainer',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '243/244',
  },
  {
    id: 'dri-levincia-244',
    name: 'Levincia',
    image: `https://den-cards.pokellector.com/412/${formatNameForUrl("Levincia")}.DRI.244.${baseUniqueId + 244 - 1}.thumb.png`,
    dataAiHint: 'Levincia stadium trainer',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '244/244',
  },
];
