
import type { PokemonCard } from './types';

// McDonald's Dragon Discovery Expansion (Match Battle 2023 - MCDP1)
// Image URLs from Pokellector: https://den-cards.pokellector.com/MCDP1/{CardName}.MCDP1.{CardNumber}.thumb.png
// Pokedex number is the card number X/15 in this specific set.

export const mcDonaldsDragonDiscoveryCards: PokemonCard[] = [
  {
    id: 'mcd-dd-charizard-001',
    name: 'Charizard',
    image: 'https://den-cards.pokellector.com/MCDP1/Charizard.MCDP1.1.thumb.png',
    dataAiHint: 'Charizard fire dragon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '1/15',
  },
  {
    id: 'mcd-dd-pikachu-002',
    name: 'Pikachu',
    image: 'https://den-cards.pokellector.com/MCDP1/Pikachu.MCDP1.2.thumb.png',
    dataAiHint: 'Pikachu electric mouse',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '2/15',
  },
  {
    id: 'mcd-dd-meowth-003',
    name: 'Meowth',
    image: 'https://den-cards.pokellector.com/MCDP1/Meowth.MCDP1.3.thumb.png',
    dataAiHint: 'Meowth cat coin',
    rarity: 'Holo Rare',
    type: 'Colorless',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '3/15',
  },
  {
    id: 'mcd-dd-rowlet-004',
    name: 'Rowlet',
    image: 'https://den-cards.pokellector.com/MCDP1/Rowlet.MCDP1.4.thumb.png',
    dataAiHint: 'Rowlet grass owl',
    rarity: 'Holo Rare',
    type: 'Grass',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '4/15',
  },
  {
    id: 'mcd-dd-hatenna-005',
    name: 'Hatenna',
    image: 'https://den-cards.pokellector.com/MCDP1/Hatenna.MCDP1.5.thumb.png',
    dataAiHint: 'Hatenna psychic small',
    rarity: 'Common',
    type: 'Psychic',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '5/15',
  },
  {
    id: 'mcd-dd-dragapult-006',
    name: 'Dragapult',
    image: 'https://den-cards.pokellector.com/MCDP1/Dragapult.MCDP1.6.thumb.png',
    dataAiHint: 'Dragapult dragon stealth',
    rarity: 'Holo Rare',
    type: 'Psychic', // Representing Ghost/Dragon
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '6/15',
  },
  {
    id: 'mcd-dd-quagsire-007',
    name: 'Quagsire',
    image: 'https://den-cards.pokellector.com/MCDP1/Quagsire.MCDP1.7.thumb.png',
    dataAiHint: 'Quagsire water ground',
    rarity: 'Common',
    type: 'Water',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '7/15',
  },
  {
    id: 'mcd-dd-gible-008',
    name: 'Gible',
    image: 'https://den-cards.pokellector.com/MCDP1/Gible.MCDP1.8.thumb.png',
    dataAiHint: 'Gible dragon land shark',
    rarity: 'Common',
    type: 'Fighting', // Representing Dragon/Ground
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '8/15',
  },
  {
    id: 'mcd-dd-umbreon-009',
    name: 'Umbreon',
    image: 'https://den-cards.pokellector.com/MCDP1/Umbreon.MCDP1.9.thumb.png',
    dataAiHint: 'Umbreon dark type',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '9/15',
  },
  {
    id: 'mcd-dd-hydreigon-010',
    name: 'Hydreigon',
    image: 'https://den-cards.pokellector.com/MCDP1/Hydreigon.MCDP1.10.thumb.png',
    dataAiHint: 'Hydreigon dark dragon',
    rarity: 'Holo Rare',
    type: 'Darkness',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '10/15',
  },
  {
    id: 'mcd-dd-roaring-moon-011',
    name: 'Roaring Moon',
    image: 'https://den-cards.pokellector.com/MCDP1/Roaring-Moon.MCDP1.11.thumb.png',
    dataAiHint: 'Roaring Moon paradox dragon',
    rarity: 'Holo Rare',
    type: 'Darkness', // Representing Dark/Dragon
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '11/15',
  },
  {
    id: 'mcd-dd-koraidon-012',
    name: 'Koraidon',
    image: 'https://den-cards.pokellector.com/MCDP1/Koraidon.MCDP1.12.thumb.png',
    dataAiHint: 'Koraidon fighting dragon',
    rarity: 'Holo Rare',
    type: 'Fighting', // Representing Fighting/Dragon
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '12/15',
  },
  {
    id: 'mcd-dd-eevee-013',
    name: 'Eevee',
    image: 'https://den-cards.pokellector.com/MCDP1/Eevee.MCDP1.13.thumb.png',
    dataAiHint: 'Eevee evolution pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '13/15',
  },
  {
    id: 'mcd-dd-rayquaza-014',
    name: 'Rayquaza',
    image: 'https://den-cards.pokellector.com/MCDP1/Rayquaza.MCDP1.14.thumb.png',
    dataAiHint: 'Rayquaza sky dragon',
    rarity: 'Holo Rare',
    type: 'Dragon', // Or Colorless, Dragon type fits well here
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '14/15',
  },
  {
    id: 'mcd-dd-drampa-015',
    name: 'Drampa',
    image: 'https://den-cards.pokellector.com/MCDP1/Drampa.MCDP1.15.thumb.png',
    dataAiHint: 'Drampa normal dragon',
    rarity: 'Common',
    type: 'Colorless', // Representing Normal/Dragon
    series: "McDonald's Dragon Discovery",
    pokedexNumber: '15/15',
  },
];
