
import type { PokemonCard } from './types';

// Destined Rivals (PAL-DR) - 58 Cards
// Image URL Pattern: https://den-cards.pokellector.com/PAL-DR/{FormattedCardName}.PAL-DR.{CardNumber}.png

export const destinedRivalsCards: PokemonCard[] = [
  {
    id: 'dr-oddish-001',
    name: 'Oddish',
    image: 'https://den-cards.pokellector.com/PAL-DR/Oddish.PAL-DR.1.png',
    dataAiHint: 'Oddish grass pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '1/58',
  },
  {
    id: 'dr-gloom-002',
    name: 'Gloom',
    image: 'https://den-cards.pokellector.com/PAL-DR/Gloom.PAL-DR.2.png',
    dataAiHint: 'Gloom weed pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '2/58',
  },
  {
    id: 'dr-vileplume-003',
    name: 'Vileplume',
    image: 'https://den-cards.pokellector.com/PAL-DR/Vileplume.PAL-DR.3.png',
    dataAiHint: 'Vileplume flower pokemon',
    rarity: 'Rare', // Non-Holo Rare
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '3/58',
  },
  {
    id: 'dr-scyther-004',
    name: 'Scyther',
    image: 'https://den-cards.pokellector.com/PAL-DR/Scyther.PAL-DR.4.png',
    dataAiHint: 'Scyther mantis pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '4/58',
  },
  {
    id: 'dr-heracross-005',
    name: 'Heracross',
    image: 'https://den-cards.pokellector.com/PAL-DR/Heracross.PAL-DR.5.png',
    dataAiHint: 'Heracross beetle pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '5/58',
  },
  {
    id: 'dr-volbeat-006',
    name: 'Volbeat',
    image: 'https://den-cards.pokellector.com/PAL-DR/Volbeat.PAL-DR.6.png',
    dataAiHint: 'Volbeat firefly pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '6/58',
  },
  {
    id: 'dr-illumise-007',
    name: 'Illumise',
    image: 'https://den-cards.pokellector.com/PAL-DR/Illumise.PAL-DR.7.png',
    dataAiHint: 'Illumise firefly pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '7/58',
  },
  {
    id: 'dr-carnivine-008',
    name: 'Carnivine',
    image: 'https://den-cards.pokellector.com/PAL-DR/Carnivine.PAL-DR.8.png',
    dataAiHint: 'Carnivine trap pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '8/58',
  },
  {
    id: 'dr-shaymin-009',
    name: 'Shaymin',
    image: 'https://den-cards.pokellector.com/PAL-DR/Shaymin.PAL-DR.9.png',
    dataAiHint: 'Shaymin gratitude pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '9/58',
  },
  {
    id: 'dr-dwebble-010',
    name: 'Dwebble',
    image: 'https://den-cards.pokellector.com/PAL-DR/Dwebble.PAL-DR.10.png',
    dataAiHint: 'Dwebble rock crab',
    rarity: 'Common',
    type: 'Grass', // Rock/Bug in games, often Grass for Bug in TCG
    series: 'Destined Rivals',
    pokedexNumber: '10/58',
  },
  {
    id: 'dr-crustle-011',
    name: 'Crustle',
    image: 'https://den-cards.pokellector.com/PAL-DR/Crustle.PAL-DR.11.png',
    dataAiHint: 'Crustle stone home pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '11/58',
  },
  {
    id: 'dr-phantump-012',
    name: 'Phantump',
    image: 'https://den-cards.pokellector.com/PAL-DR/Phantump.PAL-DR.12.png',
    dataAiHint: 'Phantump stump pokemon',
    rarity: 'Common',
    type: 'Grass', // Ghost/Grass, often Grass for secondary Grass type
    series: 'Destined Rivals',
    pokedexNumber: '12/58',
  },
  {
    id: 'dr-trevenant-013',
    name: 'Trevenant',
    image: 'https://den-cards.pokellector.com/PAL-DR/Trevenant.PAL-DR.13.png',
    dataAiHint: 'Trevenant elder tree pokemon',
    rarity: 'Rare', // Non-Holo Rare
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '13/58',
  },
  {
    id: 'dr-fomantis-014',
    name: 'Fomantis',
    image: 'https://den-cards.pokellector.com/PAL-DR/Fomantis.PAL-DR.14.png',
    dataAiHint: 'Fomantis sickle grass pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Destined Rivals',
    pokedexNumber: '14/58',
  },
  {
    id: 'dr-armarouge-ex-015',
    name: 'Armarouge ex',
    image: 'https://den-cards.pokellector.com/PAL-DR/Armarouge-ex.PAL-DR.15.png',
    dataAiHint: 'Armarouge fire warrior pokemon',
    rarity: 'Holo Rare', // ex card
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '15/58',
  },
  {
    id: 'dr-chi-yu-016',
    name: 'Chi-Yu',
    image: 'https://den-cards.pokellector.com/PAL-DR/Chi-Yu.PAL-DR.16.png',
    dataAiHint: 'Chi-Yu ruinous pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '16/58',
  },
  {
    id: 'dr-poliwag-017',
    name: 'Poliwag',
    image: 'https://den-cards.pokellector.com/PAL-DR/Poliwag.PAL-DR.17.png',
    dataAiHint: 'Poliwag tadpole pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '17/58',
  },
  {
    id: 'dr-poliwhirl-018',
    name: 'Poliwhirl',
    image: 'https://den-cards.pokellector.com/PAL-DR/Poliwhirl.PAL-DR.18.png',
    dataAiHint: 'Poliwhirl tadpole pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '18/58',
  },
  {
    id: 'dr-poliwrath-019',
    name: 'Poliwrath',
    image: 'https://den-cards.pokellector.com/PAL-DR/Poliwrath.PAL-DR.19.png',
    dataAiHint: 'Poliwrath tadpole pokemon',
    rarity: 'Rare', // Non-Holo Rare
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '19/58',
  },
  {
    id: 'dr-veluza-020',
    name: 'Veluza',
    image: 'https://den-cards.pokellector.com/PAL-DR/Veluza.PAL-DR.20.png',
    dataAiHint: 'Veluza hake pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Water',
    series: 'Destined Rivals',
    pokedexNumber: '20/58',
  },
  {
    id: 'dr-pikachu-021',
    name: 'Pikachu',
    image: 'https://den-cards.pokellector.com/PAL-DR/Pikachu.PAL-DR.21.png',
    dataAiHint: 'Pikachu mouse pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '21/58',
  },
  {
    id: 'dr-zapdos-ex-022',
    name: 'Zapdos ex',
    image: 'https://den-cards.pokellector.com/PAL-DR/Zapdos-ex.PAL-DR.22.png',
    dataAiHint: 'Zapdos electric bird pokemon',
    rarity: 'Holo Rare', // ex card
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '22/58',
  },
  {
    id: 'dr-pawmi-023',
    name: 'Pawmi',
    image: 'https://den-cards.pokellector.com/PAL-DR/Pawmi.PAL-DR.23.png',
    dataAiHint: 'Pawmi mouse pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '23/58',
  },
  {
    id: 'dr-kilowattrel-024',
    name: 'Kilowattrel',
    image: 'https://den-cards.pokellector.com/PAL-DR/Kilowattrel.PAL-DR.24.png',
    dataAiHint: 'Kilowattrel frigatebird pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '24/58',
  },
  {
    id: 'dr-iron-thorns-ex-025',
    name: 'Iron Thorns ex',
    image: 'https://den-cards.pokellector.com/PAL-DR/Iron-Thorns-ex.PAL-DR.25.png',
    dataAiHint: 'Iron Thorns paradox pokemon',
    rarity: 'Holo Rare', // ex card
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '25/58',
  },
  {
    id: 'dr-houndour-026',
    name: 'Houndour',
    image: 'https://den-cards.pokellector.com/PAL-DR/Houndour.PAL-DR.26.png',
    dataAiHint: 'Houndour dark dog pokemon',
    rarity: 'Common',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '26/58',
  },
  {
    id: 'dr-houndstone-027',
    name: 'Houndstone',
    image: 'https://den-cards.pokellector.com/PAL-DR/Houndstone.PAL-DR.27.png',
    dataAiHint: 'Houndstone ghost dog pokemon',
    rarity: 'Rare', // Non-Holo Rare
    type: 'Darkness', // Ghost in games, often Psychic or Dark in TCG
    series: 'Destined Rivals',
    pokedexNumber: '27/58',
  },
  {
    id: 'dr-absol-028',
    name: 'Absol',
    image: 'https://den-cards.pokellector.com/PAL-DR/Absol.PAL-DR.28.png',
    dataAiHint: 'Absol disaster pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '28/58',
  },
  {
    id: 'dr-darkrai-029',
    name: 'Darkrai',
    image: 'https://den-cards.pokellector.com/PAL-DR/Darkrai.PAL-DR.29.png',
    dataAiHint: 'Darkrai pitch-black pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '29/58',
  },
  {
    id: 'dr-maschiff-030',
    name: 'Maschiff',
    image: 'https://den-cards.pokellector.com/PAL-DR/Maschiff.PAL-DR.30.png',
    dataAiHint: 'Maschiff rascal pokemon',
    rarity: 'Common',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '30/58',
  },
  {
    id: 'dr-mabosstiff-031',
    name: 'Mabosstiff',
    image: 'https://den-cards.pokellector.com/PAL-DR/Mabosstiff.PAL-DR.31.png',
    dataAiHint: 'Mabosstiff boss pokemon',
    rarity: 'Uncommon',
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '31/58',
  },
  {
    id: 'dr-tinkatink-032',
    name: 'Tinkatink',
    image: 'https://den-cards.pokellector.com/PAL-DR/Tinkatink.PAL-DR.32.png',
    dataAiHint: 'Tinkatink metalsmith pokemon',
    rarity: 'Common',
    type: 'Psychic', // Fairy/Steel in games, often Psychic for Fairy
    series: 'Destined Rivals',
    pokedexNumber: '32/58',
  },
  {
    id: 'dr-tinkatuff-033',
    name: 'Tinkatuff',
    image: 'https://den-cards.pokellector.com/PAL-DR/Tinkatuff.PAL-DR.33.png',
    dataAiHint: 'Tinkatuff hammer pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '33/58',
  },
  {
    id: 'dr-tinkaton-034',
    name: 'Tinkaton',
    image: 'https://den-cards.pokellector.com/PAL-DR/Tinkaton.PAL-DR.34.png',
    dataAiHint: 'Tinkaton hammer pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '34/58',
  },
  {
    id: 'dr-flittle-035',
    name: 'Flittle',
    image: 'https://den-cards.pokellector.com/PAL-DR/Flittle.PAL-DR.35.png',
    dataAiHint: 'Flittle frill pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '35/58',
  },
  {
    id: 'dr-espathra-ex-036',
    name: 'Espathra ex',
    image: 'https://den-cards.pokellector.com/PAL-DR/Espathra-ex.PAL-DR.36.png',
    dataAiHint: 'Espathra ostrich pokemon',
    rarity: 'Holo Rare', // ex card
    type: 'Psychic',
    series: 'Destined Rivals',
    pokedexNumber: '36/58',
  },
  {
    id: 'dr-enamorus-037',
    name: 'Enamorus',
    image: 'https://den-cards.pokellector.com/PAL-DR/Enamorus.PAL-DR.37.png',
    dataAiHint: 'Enamorus love-hate pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Psychic', // Fairy/Flying, often Psychic for Fairy
    series: 'Destined Rivals',
    pokedexNumber: '37/58',
  },
  {
    id: 'dr-diancie-038',
    name: 'Diancie',
    image: 'https://den-cards.pokellector.com/PAL-DR/Diancie.PAL-DR.38.png',
    dataAiHint: 'Diancie jewel pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Psychic', // Rock/Fairy, often Psychic for Fairy
    series: 'Destined Rivals',
    pokedexNumber: '38/58',
  },
  {
    id: 'dr-dudunsparce-039',
    name: 'Dudunsparce',
    image: 'https://den-cards.pokellector.com/PAL-DR/Dudunsparce.PAL-DR.39.png',
    dataAiHint: 'Dudunsparce land snake pokemon',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '39/58',
  },
  {
    id: 'dr-zangoose-040',
    name: 'Zangoose',
    image: 'https://den-cards.pokellector.com/PAL-DR/Zangoose.PAL-DR.40.png',
    dataAiHint: 'Zangoose cat ferret pokemon',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Destined Rivals',
    pokedexNumber: '40/58',
  },
  {
    id: 'dr-swablu-041',
    name: 'Swablu',
    image: 'https://den-cards.pokellector.com/PAL-DR/Swablu.PAL-DR.41.png',
    dataAiHint: 'Swablu cotton bird pokemon',
    rarity: 'Common',
    type: 'Colorless', // Normal/Flying, often Colorless
    series: 'Destined Rivals',
    pokedexNumber: '41/58',
  },
  {
    id: 'dr-altaria-ex-042',
    name: 'Altaria ex',
    image: 'https://den-cards.pokellector.com/PAL-DR/Altaria-ex.PAL-DR.42.png',
    dataAiHint: 'Altaria humming pokemon',
    rarity: 'Holo Rare', // ex card
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '42/58',
  },
  {
    id: 'dr-hawlucha-043',
    name: 'Hawlucha',
    image: 'https://den-cards.pokellector.com/PAL-DR/Hawlucha.PAL-DR.43.png',
    dataAiHint: 'Hawlucha wrestling pokemon',
    rarity: 'Holo Rare', // Marked H
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '43/58',
  },
  {
    id: 'dr-great-tusk-ex-044',
    name: 'Great Tusk ex',
    image: 'https://den-cards.pokellector.com/PAL-DR/Great-Tusk-ex.PAL-DR.44.png',
    dataAiHint: 'Great Tusk paradox pokemon',
    rarity: 'Holo Rare', // ex card
    type: 'Fighting',
    series: 'Destined Rivals',
    pokedexNumber: '44/58',
  },
  {
    id: 'dr-iron-valiant-ex-045',
    name: 'Iron Valiant ex',
    image: 'https://den-cards.pokellector.com/PAL-DR/Iron-Valiant-ex.PAL-DR.45.png',
    dataAiHint: 'Iron Valiant paradox pokemon',
    rarity: 'Holo Rare', // ex card
    type: 'Psychic', // Fairy/Fighting, often Psychic
    series: 'Destined Rivals',
    pokedexNumber: '45/58',
  },
  {
    id: 'dr-tm-crisis-punch-046',
    name: 'Technical Machine: Crisis Punch',
    image: 'https://den-cards.pokellector.com/PAL-DR/Technical-Machine-Crisis-Punch.PAL-DR.46.png',
    dataAiHint: 'TM Crisis Punch',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '46/58',
  },
  {
    id: 'dr-tm-turbo-energize-047',
    name: 'Technical Machine: Turbo Energize',
    image: 'https://den-cards.pokellector.com/PAL-DR/Technical-Machine-Turbo-Energize.PAL-DR.47.png',
    dataAiHint: 'TM Turbo Energize',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '47/58',
  },
  {
    id: 'dr-grabber-048',
    name: 'Grabber',
    image: 'https://den-cards.pokellector.com/PAL-DR/Grabber.PAL-DR.48.png',
    dataAiHint: 'Grabber trainer item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '48/58',
  },
  {
    id: 'dr-rescue-board-049',
    name: 'Rescue Board',
    image: 'https://den-cards.pokellector.com/PAL-DR/Rescue-Board.PAL-DR.49.png',
    dataAiHint: 'Rescue Board trainer tool',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '49/58',
  },
  {
    id: 'dr-hand-trimmer-050',
    name: 'Hand Trimmer',
    image: 'https://den-cards.pokellector.com/PAL-DR/Hand-Trimmer.PAL-DR.50.png',
    dataAiHint: 'Hand Trimmer trainer item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '50/58',
  },
  {
    id: 'dr-mortys-conviction-051',
    name: "Morty's Conviction",
    image: 'https://den-cards.pokellector.com/PAL-DR/Mortys-Conviction.PAL-DR.51.png',
    dataAiHint: 'Morty trainer supporter',
    rarity: 'Holo Rare', // IR card
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '51/58',
  },
  {
    id: 'dr-salvatore-052',
    name: 'Salvatore',
    image: 'https://den-cards.pokellector.com/PAL-DR/Salvatore.PAL-DR.52.png',
    dataAiHint: 'Salvatore trainer supporter',
    rarity: 'Holo Rare', // IR card
    type: 'Trainer',
    series: 'Destined Rivals',
    pokedexNumber: '52/58',
  },
  {
    id: 'dr-armarouge-ex-sir-053',
    name: 'Armarouge ex', // SIR
    image: 'https://den-cards.pokellector.com/PAL-DR/Armarouge-ex.PAL-DR.53.png',
    dataAiHint: 'Armarouge ex special art',
    rarity: 'Holo Rare', // SIR card
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '53/58',
  },
  {
    id: 'dr-chi-yu-ir-054',
    name: 'Chi-Yu', // IR
    image: 'https://den-cards.pokellector.com/PAL-DR/Chi-Yu.PAL-DR.54.png',
    dataAiHint: 'Chi-Yu illustration rare',
    rarity: 'Holo Rare', // IR card
    type: 'Fire',
    series: 'Destined Rivals',
    pokedexNumber: '54/58',
  },
  {
    id: 'dr-zapdos-ex-sir-055',
    name: 'Zapdos ex', // SIR
    image: 'https://den-cards.pokellector.com/PAL-DR/Zapdos-ex.PAL-DR.55.png',
    dataAiHint: 'Zapdos ex special art',
    rarity: 'Holo Rare', // SIR card
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '55/58',
  },
  {
    id: 'dr-iron-thorns-ex-sir-056',
    name: 'Iron Thorns ex', // SIR
    image: 'https://den-cards.pokellector.com/PAL-DR/Iron-Thorns-ex.PAL-DR.56.png',
    dataAiHint: 'Iron Thorns ex special art',
    rarity: 'Holo Rare', // SIR card
    type: 'Lightning',
    series: 'Destined Rivals',
    pokedexNumber: '56/58',
  },
  {
    id: 'dr-darkrai-ir-057',
    name: 'Darkrai', // IR
    image: 'https://den-cards.pokellector.com/PAL-DR/Darkrai.PAL-DR.57.png',
    dataAiHint: 'Darkrai illustration rare',
    rarity: 'Holo Rare', // IR card
    type: 'Darkness',
    series: 'Destined Rivals',
    pokedexNumber: '57/58',
  },
  {
    id: 'dr-altaria-ex-sir-058',
    name: 'Altaria ex', // SIR
    image: 'https://den-cards.pokellector.com/PAL-DR/Altaria-ex.PAL-DR.58.png',
    dataAiHint: 'Altaria ex special art',
    rarity: 'Holo Rare', // SIR card
    type: 'Dragon',
    series: 'Destined Rivals',
    pokedexNumber: '58/58',
  },
];
