
import type { PokemonCard } from './types';

// Comprehensive Base Set Card List
// Card images use https://den-cards.pokellector.com/119/{CardName}.BS.{CardNumber}.{OptionalID}.png format.
// Pokedex number is the card number in the set, e.g., "1/102".

export const baseSetCards: PokemonCard[] = [
  // Holo Rares (1/102 to 16/102)
  {
    id: 'base-alakazam-001',
    name: 'Alakazam',
    image: 'https://den-cards.pokellector.com/119/Alakazam.BS.1.png',
    dataAiHint: 'Alakazam psychic pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Base Set',
    pokedexNumber: '1/102',
  },
  {
    id: 'base-blastoise-002',
    name: 'Blastoise',
    image: 'https://den-cards.pokellector.com/119/Blastoise.BS.2.png',
    dataAiHint: 'Blastoise water turtle pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '2/102',
  },
  {
    id: 'base-chansey-003',
    name: 'Chansey',
    image: 'https://den-cards.pokellector.com/119/Chansey.BS.3.png',
    dataAiHint: 'Chansey egg pokemon',
    rarity: 'Holo Rare',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '3/102',
  },
  {
    id: 'base-charizard-004',
    name: 'Charizard',
    image: 'https://den-cards.pokellector.com/119/Charizard.BS.4.png',
    dataAiHint: 'Charizard flying fire dragon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '4/102',
  },
  {
    id: 'base-clefairy-005',
    name: 'Clefairy',
    image: 'https://den-cards.pokellector.com/119/Clefairy.BS.5.png',
    dataAiHint: 'Clefairy fairy pokemon',
    rarity: 'Holo Rare',
    type: 'Colorless', // Often Colorless in early TCG, despite Fairy game type
    series: 'Base Set',
    pokedexNumber: '5/102',
  },
  {
    id: 'base-gyarados-006',
    name: 'Gyarados',
    image: 'https://den-cards.pokellector.com/119/Gyarados.BS.6.png',
    dataAiHint: 'Gyarados water flying pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '6/102',
  },
  {
    id: 'base-hitmonchan-007',
    name: 'Hitmonchan',
    image: 'https://den-cards.pokellector.com/119/Hitmonchan.BS.7.png',
    dataAiHint: 'Hitmonchan fighting pokemon',
    rarity: 'Holo Rare',
    type: 'Fighting',
    series: 'Base Set',
    pokedexNumber: '7/102',
  },
  {
    id: 'base-machamp-008',
    name: 'Machamp',
    image: 'https://den-cards.pokellector.com/119/Machamp.BS.8.png',
    dataAiHint: 'Machamp fighting pokemon',
    rarity: 'Holo Rare', // Starter Deck exclusive, but Holo
    type: 'Fighting',
    series: 'Base Set',
    pokedexNumber: '8/102',
  },
  {
    id: 'base-magneton-009',
    name: 'Magneton',
    image: 'https://den-cards.pokellector.com/119/Magneton.BS.9.png',
    dataAiHint: 'Magneton electric steel pokemon',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '9/102',
  },
  {
    id: 'base-mewtwo-010',
    name: 'Mewtwo',
    image: 'https://den-cards.pokellector.com/119/Mewtwo.BS.10.png',
    dataAiHint: 'Mewtwo legendary psychic pokemon',
    rarity: 'Holo Rare',
    type: 'Psychic',
    series: 'Base Set',
    pokedexNumber: '10/102',
  },
  {
    id: 'base-nidoking-011',
    name: 'Nidoking',
    image: 'https://den-cards.pokellector.com/119/Nidoking.BS.11.png',
    dataAiHint: 'Nidoking poison ground pokemon',
    rarity: 'Holo Rare',
    type: 'Grass', // Poison types are often Grass in early TCG
    series: 'Base Set',
    pokedexNumber: '11/102',
  },
  {
    id: 'base-ninetales-012',
    name: 'Ninetales',
    image: 'https://den-cards.pokellector.com/119/Ninetales.BS.12.png',
    dataAiHint: 'Ninetales fire fox pokemon',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '12/102',
  },
  {
    id: 'base-poliwrath-013',
    name: 'Poliwrath',
    image: 'https://den-cards.pokellector.com/119/Poliwrath.BS.13.png',
    dataAiHint: 'Poliwrath water fighting pokemon',
    rarity: 'Holo Rare',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '13/102',
  },
  {
    id: 'base-raichu-014',
    name: 'Raichu',
    image: 'https://den-cards.pokellector.com/119/Raichu.BS.14.png',
    dataAiHint: 'Raichu electric mouse pokemon',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '14/102',
  },
  {
    id: 'base-venusaur-015',
    name: 'Venusaur',
    image: 'https://den-cards.pokellector.com/119/Venusaur.BS.15.png',
    dataAiHint: 'Venusaur flower pokemon',
    rarity: 'Holo Rare',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '15/102',
  },
  {
    id: 'base-zapdos-016',
    name: 'Zapdos',
    image: 'https://den-cards.pokellector.com/119/Zapdos.BS.16.png',
    dataAiHint: 'Zapdos legendary electric bird',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '16/102',
  },

  // Rares (Non-Holo Pokemon: 17/102 to 22/102 and Trainers 70/102 to 79/102)
  {
    id: 'base-beedrill-017',
    name: 'Beedrill',
    image: 'https://den-cards.pokellector.com/119/Beedrill.BS.17.png',
    dataAiHint: 'Beedrill poison bee pokemon',
    rarity: 'Rare',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '17/102',
  },
  {
    id: 'base-dragonair-018',
    name: 'Dragonair',
    image: 'https://den-cards.pokellector.com/119/Dragonair.BS.18.png',
    dataAiHint: 'Dragonair dragon pokemon',
    rarity: 'Rare',
    type: 'Colorless', // Dragon types were Colorless in Base Set
    series: 'Base Set',
    pokedexNumber: '18/102',
  },
  {
    id: 'base-dugtrio-019',
    name: 'Dugtrio',
    image: 'https://den-cards.pokellector.com/119/Dugtrio.BS.19.png',
    dataAiHint: 'Dugtrio ground pokemon',
    rarity: 'Rare',
    type: 'Fighting', // Ground types were often Fighting
    series: 'Base Set',
    pokedexNumber: '19/102',
  },
  {
    id: 'base-electabuzz-020',
    name: 'Electabuzz',
    image: 'https://den-cards.pokellector.com/119/Electabuzz.BS.20.png',
    dataAiHint: 'Electabuzz electric pokemon',
    rarity: 'Rare',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '20/102',
  },
  {
    id: 'base-electrode-021',
    name: 'Electrode',
    image: 'https://den-cards.pokellector.com/119/Electrode.BS.21.png',
    dataAiHint: 'Electrode ball pokemon',
    rarity: 'Rare',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '21/102',
  },
  {
    id: 'base-pidgeotto-022', // Often considered Rare, sometimes Uncommon in some lists
    name: 'Pidgeotto',
    image: 'https://den-cards.pokellector.com/119/Pidgeotto.BS.22.png',
    dataAiHint: 'Pidgeotto bird pokemon',
    rarity: 'Rare',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '22/102',
  },
  {
    id: 'base-clefairy-doll-070',
    name: 'Clefairy Doll',
    image: 'https://den-cards.pokellector.com/119/Clefairy-Doll.BS.70.png',
    dataAiHint: 'Clefairy Doll trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '70/102',
  },
  {
    id: 'base-computer-search-071',
    name: 'Computer Search',
    image: 'https://den-cards.pokellector.com/119/Computer-Search.BS.71.png',
    dataAiHint: 'Computer Search trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '71/102',
  },
  {
    id: 'base-devolution-spray-072',
    name: 'Devolution Spray',
    image: 'https://den-cards.pokellector.com/119/Devolution-Spray.BS.72.png',
    dataAiHint: 'Devolution Spray trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '72/102',
  },
  {
    id: 'base-imposter-professor-oak-073',
    name: 'Imposter Professor Oak',
    image: 'https://den-cards.pokellector.com/119/Imposter-Professor-Oak.BS.73.png',
    dataAiHint: 'Imposter Professor Oak trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '73/102',
  },
  {
    id: 'base-item-finder-074',
    name: 'Item Finder',
    image: 'https://den-cards.pokellector.com/119/Item-Finder.BS.74.png',
    dataAiHint: 'Item Finder trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '74/102',
  },
  {
    id: 'base-lass-075',
    name: 'Lass',
    image: 'https://den-cards.pokellector.com/119/Lass.BS.75.png',
    dataAiHint: 'Lass pokemon trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '75/102',
  },
  {
    id: 'base-pokemon-breeder-076',
    name: 'Pokémon Breeder',
    image: 'https://den-cards.pokellector.com/119/Pokemon-Breeder.BS.76.png',
    dataAiHint: 'Pokemon Breeder trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '76/102',
  },
  {
    id: 'base-pokemon-trader-077',
    name: 'Pokémon Trader',
    image: 'https://den-cards.pokellector.com/119/Pokemon-Trader.BS.77.png',
    dataAiHint: 'Pokemon Trader trainer',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '77/102',
  },
  {
    id: 'base-scoop-up-078',
    name: 'Scoop Up',
    image: 'https://den-cards.pokellector.com/119/Scoop-Up.BS.78.png',
    dataAiHint: 'Scoop Up item',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '78/102',
  },
  {
    id: 'base-super-energy-removal-079',
    name: 'Super Energy Removal',
    image: 'https://den-cards.pokellector.com/119/Super-Energy-Removal.BS.79.png',
    dataAiHint: 'Super Energy Removal item',
    rarity: 'Rare',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '79/102',
  },

  // Uncommons (Pokemon: 23/102 to 42/102, Trainers 80/102 to 90/102, Energy 96/102)
  {
    id: 'base-arcanine-023',
    name: 'Arcanine',
    image: 'https://den-cards.pokellector.com/119/Arcanine.BS.23.png',
    dataAiHint: 'Arcanine legendary fire dog',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '23/102',
  },
  {
    id: 'base-charmeleon-024',
    name: 'Charmeleon',
    image: 'https://den-cards.pokellector.com/119/Charmeleon.BS.24.png',
    dataAiHint: 'Charmeleon fire pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '24/102',
  },
  {
    id: 'base-dewgong-025',
    name: 'Dewgong',
    image: 'https://den-cards.pokellector.com/119/Dewgong.BS.25.png',
    dataAiHint: 'Dewgong water ice sea lion',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '25/102',
  },
  {
    id: 'base-dratini-026',
    name: 'Dratini',
    image: 'https://den-cards.pokellector.com/119/Dratini.BS.26.png',
    dataAiHint: 'Dratini dragon pokemon',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '26/102',
  },
  {
    id: 'base-farfetchd-027',
    name: 'Farfetch\'d',
    image: 'https://den-cards.pokellector.com/119/Farfetchd.BS.27.png',
    dataAiHint: 'Farfetchd bird leek',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '27/102',
  },
  {
    id: 'base-growlithe-028',
    name: 'Growlithe',
    image: 'https://den-cards.pokellector.com/119/Growlithe.BS.28.png',
    dataAiHint: 'Growlithe puppy pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '28/102',
  },
  {
    id: 'base-haunter-029',
    name: 'Haunter',
    image: 'https://den-cards.pokellector.com/119/Haunter.BS.29.png',
    dataAiHint: 'Haunter gas ghost pokemon',
    rarity: 'Uncommon',
    type: 'Psychic', // Ghost types often Psychic
    series: 'Base Set',
    pokedexNumber: '29/102',
  },
  {
    id: 'base-ivysaur-030',
    name: 'Ivysaur',
    image: 'https://den-cards.pokellector.com/119/Ivysaur.BS.30.png',
    dataAiHint: 'Ivysaur bud pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '30/102',
  },
  {
    id: 'base-jynx-031',
    name: 'Jynx',
    image: 'https://den-cards.pokellector.com/119/Jynx.BS.31.png',
    dataAiHint: 'Jynx psychic ice pokemon',
    rarity: 'Uncommon',
    type: 'Psychic', // Ice types often Psychic or Water
    series: 'Base Set',
    pokedexNumber: '31/102',
  },
  {
    id: 'base-kadabra-032',
    name: 'Kadabra',
    image: 'https://den-cards.pokellector.com/119/Kadabra.BS.32.png',
    dataAiHint: 'Kadabra psychic pokemon',
    rarity: 'Uncommon',
    type: 'Psychic',
    series: 'Base Set',
    pokedexNumber: '32/102',
  },
  {
    id: 'base-kakuna-033',
    name: 'Kakuna',
    image: 'https://den-cards.pokellector.com/119/Kakuna.BS.33.png',
    dataAiHint: 'Kakuna cocoon pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '33/102',
  },
  {
    id: 'base-machoke-034',
    name: 'Machoke',
    image: 'https://den-cards.pokellector.com/119/Machoke.BS.34.png',
    dataAiHint: 'Machoke fighting pokemon',
    rarity: 'Uncommon',
    type: 'Fighting',
    series: 'Base Set',
    pokedexNumber: '34/102',
  },
  {
    id: 'base-magikarp-035',
    name: 'Magikarp',
    image: 'https://den-cards.pokellector.com/119/Magikarp.BS.35.png',
    dataAiHint: 'Magikarp fish pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '35/102',
  },
  {
    id: 'base-magmar-036',
    name: 'Magmar',
    image: 'https://den-cards.pokellector.com/119/Magmar.BS.36.png',
    dataAiHint: 'Magmar fire pokemon',
    rarity: 'Uncommon',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '36/102',
  },
  {
    id: 'base-nidorino-037',
    name: 'Nidorino',
    image: 'https://den-cards.pokellector.com/119/Nidorino.BS.37.png',
    dataAiHint: 'Nidorino poison pokemon',
    rarity: 'Uncommon',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '37/102',
  },
  {
    id: 'base-poliwhirl-038',
    name: 'Poliwhirl',
    image: 'https://den-cards.pokellector.com/119/Poliwhirl.BS.38.png',
    dataAiHint: 'Poliwhirl tadpole pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '38/102',
  },
  {
    id: 'base-porygon-039',
    name: 'Porygon',
    image: 'https://den-cards.pokellector.com/119/Porygon.BS.39.png',
    dataAiHint: 'Porygon virtual pokemon',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '39/102',
  },
  {
    id: 'base-raticate-040',
    name: 'Raticate',
    image: 'https://den-cards.pokellector.com/119/Raticate.BS.40.png',
    dataAiHint: 'Raticate mouse pokemon',
    rarity: 'Uncommon',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '40/102',
  },
  {
    id: 'base-seel-041',
    name: 'Seel',
    image: 'https://den-cards.pokellector.com/119/Seel.BS.41.png',
    dataAiHint: 'Seel sea lion pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '41/102',
  },
  {
    id: 'base-wartortle-042',
    name: 'Wartortle',
    image: 'https://den-cards.pokellector.com/119/Wartortle.BS.42.png',
    dataAiHint: 'Wartortle turtle pokemon',
    rarity: 'Uncommon',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '42/102',
  },
  {
    id: 'base-defender-080',
    name: 'Defender',
    image: 'https://den-cards.pokellector.com/119/Defender.BS.80.png',
    dataAiHint: 'Defender trainer item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '80/102',
  },
  {
    id: 'base-energy-retrieval-081',
    name: 'Energy Retrieval',
    image: 'https://den-cards.pokellector.com/119/Energy-Retrieval.BS.81.png',
    dataAiHint: 'Energy Retrieval trainer',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '81/102',
  },
  {
    id: 'base-full-heal-082',
    name: 'Full Heal',
    image: 'https://den-cards.pokellector.com/119/Full-Heal.BS.82.png',
    dataAiHint: 'Full Heal trainer item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '82/102',
  },
  {
    id: 'base-maintenance-083',
    name: 'Maintenance',
    image: 'https://den-cards.pokellector.com/119/Maintenance.BS.83.png',
    dataAiHint: 'Maintenance trainer',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '83/102',
  },
  {
    id: 'base-pluspower-084',
    name: 'PlusPower',
    image: 'https://den-cards.pokellector.com/119/PlusPower.BS.84.png',
    dataAiHint: 'PlusPower trainer item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '84/102',
  },
  {
    id: 'base-pokemon-center-085',
    name: 'Pokémon Center',
    image: 'https://den-cards.pokellector.com/119/Pokemon-Center.BS.85.png',
    dataAiHint: 'Pokemon Center stadium',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '85/102',
  },
  {
    id: 'base-pokemon-flute-086',
    name: 'Pokémon Flute',
    image: 'https://den-cards.pokellector.com/119/Pokemon-Flute.BS.86.png',
    dataAiHint: 'Pokemon Flute item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '86/102',
  },
  {
    id: 'base-pokedex-087',
    name: 'Pokédex',
    image: 'https://den-cards.pokellector.com/119/Pokedex.BS.87.png',
    dataAiHint: 'Pokedex trainer item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '87/102',
  },
  {
    id: 'base-professor-oak-088',
    name: 'Professor Oak',
    image: 'https://den-cards.pokellector.com/119/Professor-Oak.BS.88.png',
    dataAiHint: 'Professor Oak pokemon trainer',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '88/102',
  },
  {
    id: 'base-revive-089',
    name: 'Revive',
    image: 'https://den-cards.pokellector.com/119/Revive.BS.89.png',
    dataAiHint: 'Revive trainer item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '89/102',
  },
  {
    id: 'base-super-potion-090',
    name: 'Super Potion',
    image: 'https://den-cards.pokellector.com/119/Super-Potion.BS.90.png',
    dataAiHint: 'Super Potion item',
    rarity: 'Uncommon',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '90/102',
  },
  {
    id: 'base-double-colorless-energy-096',
    name: 'Double Colorless Energy',
    image: 'https://den-cards.pokellector.com/119/Double-Colorless-Energy.BS.96.png',
    dataAiHint: 'Double colorless energy',
    rarity: 'Uncommon',
    type: 'Energy',
    series: 'Base Set',
    pokedexNumber: '96/102',
  },

  // Commons (Pokemon: 43/102 to 69/102, Trainers 91/102 to 95/102, Basic Energies 97/102 to 102/102)
  {
    id: 'base-abra-043',
    name: 'Abra',
    image: 'https://den-cards.pokellector.com/119/Abra.BS.43.png',
    dataAiHint: 'Abra psychic pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Base Set',
    pokedexNumber: '43/102',
  },
  {
    id: 'base-bulbasaur-044',
    name: 'Bulbasaur',
    image: 'https://den-cards.pokellector.com/119/Bulbasaur.BS.44.png',
    dataAiHint: 'Bulbasaur seed pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '44/102',
  },
  {
    id: 'base-caterpie-045',
    name: 'Caterpie',
    image: 'https://den-cards.pokellector.com/119/Caterpie.BS.45.png',
    dataAiHint: 'Caterpie worm pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '45/102',
  },
  {
    id: 'base-charmander-046',
    name: 'Charmander',
    image: 'https://den-cards.pokellector.com/119/Charmander.BS.46.png',
    dataAiHint: 'Charmander flame pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '46/102',
  },
  {
    id: 'base-diglett-047',
    name: 'Diglett',
    image: 'https://den-cards.pokellector.com/119/Diglett.BS.47.png',
    dataAiHint: 'Diglett mole pokemon',
    rarity: 'Common',
    type: 'Fighting',
    series: 'Base Set',
    pokedexNumber: '47/102',
  },
  {
    id: 'base-doduo-048',
    name: 'Doduo',
    image: 'https://den-cards.pokellector.com/119/Doduo.BS.48.png',
    dataAiHint: 'Doduo twin bird pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '48/102',
  },
  {
    id: 'base-drowzee-049',
    name: 'Drowzee',
    image: 'https://den-cards.pokellector.com/119/Drowzee.BS.49.png',
    dataAiHint: 'Drowzee hypnosis pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Base Set',
    pokedexNumber: '49/102',
  },
  {
    id: 'base-gastly-050',
    name: 'Gastly',
    image: 'https://den-cards.pokellector.com/119/Gastly.BS.50.png',
    dataAiHint: 'Gastly gas pokemon',
    rarity: 'Common',
    type: 'Psychic',
    series: 'Base Set',
    pokedexNumber: '50/102',
  },
  {
    id: 'base-koffing-051',
    name: 'Koffing',
    image: 'https://den-cards.pokellector.com/119/Koffing.BS.51.png',
    dataAiHint: 'Koffing poison gas pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '51/102',
  },
  {
    id: 'base-machop-052',
    name: 'Machop',
    image: 'https://den-cards.pokellector.com/119/Machop.BS.52.png',
    dataAiHint: 'Machop fighting pokemon',
    rarity: 'Common',
    type: 'Fighting',
    series: 'Base Set',
    pokedexNumber: '52/102',
  },
  {
    id: 'base-magnemite-053',
    name: 'Magnemite',
    image: 'https://den-cards.pokellector.com/119/Magnemite.BS.53.png',
    dataAiHint: 'Magnemite magnet pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '53/102',
  },
  {
    id: 'base-metapod-054',
    name: 'Metapod',
    image: 'https://den-cards.pokellector.com/119/Metapod.BS.54.png',
    dataAiHint: 'Metapod cocoon pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '54/102',
  },
  {
    id: 'base-nidoran-male-055',
    name: 'Nidoran ♂',
    image: 'https://den-cards.pokellector.com/119/Nidoran-M.BS.55.png',
    dataAiHint: 'Nidoran male poison pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '55/102',
  },
  {
    id: 'base-onix-056',
    name: 'Onix',
    image: 'https://den-cards.pokellector.com/119/Onix.BS.56.png',
    dataAiHint: 'Onix rock snake pokemon',
    rarity: 'Common',
    type: 'Fighting',
    series: 'Base Set',
    pokedexNumber: '56/102',
  },
  {
    id: 'base-pidgey-057',
    name: 'Pidgey',
    image: 'https://den-cards.pokellector.com/119/Pidgey.BS.57.png',
    dataAiHint: 'Pidgey tiny bird pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '57/102',
  },
  {
    id: 'base-pikachu-058',
    name: 'Pikachu',
    image: 'https://den-cards.pokellector.com/119/Pikachu.BS.58.png', // Standard yellow cheeks Pikachu
    dataAiHint: 'Pikachu electric mouse pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '58/102',
  },
  {
    id: 'base-poliwag-059',
    name: 'Poliwag',
    image: 'https://den-cards.pokellector.com/119/Poliwag.BS.59.png',
    dataAiHint: 'Poliwag tadpole pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '59/102',
  },
  {
    id: 'base-ponyta-060',
    name: 'Ponyta',
    image: 'https://den-cards.pokellector.com/119/Ponyta.BS.60.png',
    dataAiHint: 'Ponyta fire horse pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '60/102',
  },
  {
    id: 'base-rattata-061',
    name: 'Rattata',
    image: 'https://den-cards.pokellector.com/119/Rattata.BS.61.png',
    dataAiHint: 'Rattata mouse pokemon',
    rarity: 'Common',
    type: 'Colorless',
    series: 'Base Set',
    pokedexNumber: '61/102',
  },
  {
    id: 'base-sandshrew-062',
    name: 'Sandshrew',
    image: 'https://den-cards.pokellector.com/119/Sandshrew.BS.62.png',
    dataAiHint: 'Sandshrew mouse ground pokemon',
    rarity: 'Common',
    type: 'Fighting',
    series: 'Base Set',
    pokedexNumber: '62/102',
  },
  {
    id: 'base-squirtle-063',
    name: 'Squirtle',
    image: 'https://den-cards.pokellector.com/119/Squirtle.BS.63.png',
    dataAiHint: 'Squirtle shell pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '63/102',
  },
  {
    id: 'base-starmie-064',
    name: 'Starmie',
    image: 'https://den-cards.pokellector.com/119/Starmie.BS.64.png',
    dataAiHint: 'Starmie star water psychic',
    rarity: 'Common',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '64/102',
  },
  {
    id: 'base-staryu-065',
    name: 'Staryu',
    image: 'https://den-cards.pokellector.com/119/Staryu.BS.65.png',
    dataAiHint: 'Staryu star water pokemon',
    rarity: 'Common',
    type: 'Water',
    series: 'Base Set',
    pokedexNumber: '65/102',
  },
  {
    id: 'base-tangela-066',
    name: 'Tangela',
    image: 'https://den-cards.pokellector.com/119/Tangela.BS.66.png',
    dataAiHint: 'Tangela vine pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '66/102',
  },
  {
    id: 'base-voltorb-067',
    name: 'Voltorb',
    image: 'https://den-cards.pokellector.com/119/Voltorb.BS.67.png',
    dataAiHint: 'Voltorb ball pokemon',
    rarity: 'Common',
    type: 'Lightning',
    series: 'Base Set',
    pokedexNumber: '67/102',
  },
  {
    id: 'base-vulpix-068',
    name: 'Vulpix',
    image: 'https://den-cards.pokellector.com/119/Vulpix.BS.68.png',
    dataAiHint: 'Vulpix fox fire pokemon',
    rarity: 'Common',
    type: 'Fire',
    series: 'Base Set',
    pokedexNumber: '68/102',
  },
  {
    id: 'base-weedle-069',
    name: 'Weedle',
    image: 'https://den-cards.pokellector.com/119/Weedle.BS.69.png',
    dataAiHint: 'Weedle hairy bug pokemon',
    rarity: 'Common',
    type: 'Grass',
    series: 'Base Set',
    pokedexNumber: '69/102',
  },
  {
    id: 'base-bill-091',
    name: 'Bill',
    image: 'https://den-cards.pokellector.com/119/Bill.BS.91.png',
    dataAiHint: 'Bill pokemon trainer',
    rarity: 'Common',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '91/102',
  },
  {
    id: 'base-energy-removal-092',
    name: 'Energy Removal',
    image: 'https://den-cards.pokellector.com/119/Energy-Removal.BS.92.png',
    dataAiHint: 'Energy Removal item',
    rarity: 'Common',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '92/102',
  },
  {
    id: 'base-gust-of-wind-093',
    name: 'Gust of Wind',
    image: 'https://den-cards.pokellector.com/119/Gust-of-Wind.BS.93.png',
    dataAiHint: 'Gust of Wind item',
    rarity: 'Common',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '93/102',
  },
  {
    id: 'base-potion-094',
    name: 'Potion',
    image: 'https://den-cards.pokellector.com/119/Potion.BS.94.png',
    dataAiHint: 'Potion pokemon item',
    rarity: 'Common',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '94/102',
  },
  {
    id: 'base-switch-095',
    name: 'Switch',
    image: 'https://den-cards.pokellector.com/119/Switch.BS.95.7933.png',
    dataAiHint: 'Switch item',
    rarity: 'Common',
    type: 'Trainer',
    series: 'Base Set',
    pokedexNumber: '95/102',
  },
  {
    id: 'base-fighting-energy-097',
    name: 'Fighting Energy',
    image: 'https://den-cards.pokellector.com/119/Fighting-Energy.BS.97.png',
    dataAiHint: 'Fighting energy symbol',
    rarity: 'Common', // Basic energies are effectively common
    type: 'Energy',
    series: 'Base Set',
    pokedexNumber: '97/102',
  },
  {
    id: 'base-fire-energy-098',
    name: 'Fire Energy',
    image: 'https://den-cards.pokellector.com/119/Fire-Energy.BS.98.png',
    dataAiHint: 'Fire energy symbol',
    rarity: 'Common',
    type: 'Energy',
    series: 'Base Set',
    pokedexNumber: '98/102',
  },
  {
    id: 'base-grass-energy-099',
    name: 'Grass Energy',
    image: 'https://den-cards.pokellector.com/119/Grass-Energy.BS.99.png',
    dataAiHint: 'Grass energy symbol',
    rarity: 'Common',
    type: 'Energy',
    series: 'Base Set',
    pokedexNumber: '99/102',
  },
  {
    id: 'base-lightning-energy-100',
    name: 'Lightning Energy',
    image: 'https://den-cards.pokellector.com/119/Lightning-Energy.BS.100.png',
    dataAiHint: 'Lightning energy symbol',
    rarity: 'Common',
    type: 'Energy',
    series: 'Base Set',
    pokedexNumber: '100/102',
  },
  {
    id: 'base-psychic-energy-101',
    name: 'Psychic Energy',
    image: 'https://den-cards.pokellector.com/119/Psychic-Energy.BS.101.png',
    dataAiHint: 'Psychic energy symbol',
    rarity: 'Common',
    type: 'Energy',
    series: 'Base Set',
    pokedexNumber: '101/102',
  },
  {
    id: 'base-water-energy-102',
    name: 'Water Energy',
    image: 'https://den-cards.pokellector.com/119/Water-Energy.BS.102.png',
    dataAiHint: 'Water energy symbol',
    rarity: 'Common',
    type: 'Energy',
    series: 'Base Set',
    pokedexNumber: '102/102',
  },
];
