import type { PokemonCard, PokemonPack, PokemonType, CardRarity } from './types';

export const allCards: PokemonCard[] = [
  // Commons
  {
    id: 'pika001',
    name: 'Pikachu',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Pikachu smiling',
    rarity: 'Common',
    type: 'Lightning',
    hp: 60,
    attacks: [{ name: 'Quick Attack', damage: '10+', description: 'Flip a coin. If heads, this attack does 10 more damage.' }],
    weaknesses: [{ type: 'Fighting', value: 'x2' }],
    retreatCost: 1,
    description: 'A very popular Pokémon, known for its electric cheeks.',
    series: 'Spark Series',
  },
  {
    id: 'bulb001',
    name: 'Bulbasaur',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Bulbasaur cute',
    rarity: 'Common',
    type: 'Grass',
    hp: 70,
    attacks: [{ name: 'Vine Whip', damage: '20', description: '' }],
    weaknesses: [{ type: 'Fire', value: 'x2' }],
    retreatCost: 1,
    description: 'A strange seed was planted on its back at birth.',
    series: 'Spark Series',
  },
  {
    id: 'char001',
    name: 'Charmander',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Charmander flame',
    rarity: 'Common',
    type: 'Fire',
    hp: 70,
    attacks: [{ name: 'Scratch', damage: '10', description: ''}, { name: 'Ember', damage: '30', description: 'Discard 1 Fire Energy.'}],
    weaknesses: [{ type: 'Water', value: 'x2' }],
    retreatCost: 1,
    description: 'The flame on its tail indicates its life force.',
    series: 'Spark Series',
  },
  {
    id: 'squi001',
    name: 'Squirtle',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Squirtle water',
    rarity: 'Common',
    type: 'Water',
    hp: 60,
    attacks: [{ name: 'Bubble', damage: '10', description: 'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.' }],
    weaknesses: [{ type: 'Grass', value: 'x2' }],
    retreatCost: 1,
    description: 'It shelters itself in its shell, then strikes back with spouts of water.',
    series: 'Spark Series',
  },
  {
    id: 'ratt001',
    name: 'Rattata',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Rattata purple',
    rarity: 'Common',
    type: 'Colorless',
    hp: 40,
    attacks: [{ name: 'Bite', damage: '20', description: '' }],
    weaknesses: [{ type: 'Fighting', value: 'x2' }],
    retreatCost: 0,
    description: 'Bites anything when it attacks. Small and very quick.',
    series: 'Spark Series',
  },
  {
    id: 'mank001',
    name: 'Mankey',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Mankey angry',
    rarity: 'Common',
    type: 'Fighting',
    hp: 50,
    attacks: [{ name: 'Low Kick', damage: '20', description: '' }],
    weaknesses: [{ type: 'Psychic', value: 'x2' }],
    retreatCost: 1,
    description: 'Extremely quick to anger. It could be docile one moment then thrashing wildly the next.',
    series: 'Spark Series',
  },

  // Uncommons
  {
    id: 'ivys001',
    name: 'Ivysaur',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Ivysaur flower',
    rarity: 'Uncommon',
    type: 'Grass',
    hp: 100,
    attacks: [{ name: 'Razor Leaf', damage: '40', description: '' }],
    weaknesses: [{ type: 'Fire', value: 'x2' }],
    retreatCost: 2,
    description: 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.',
    series: 'Spark Series',
  },
  {
    id: 'wart001',
    name: 'Wartortle',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Wartortle tail',
    rarity: 'Uncommon',
    type: 'Water',
    hp: 90,
    attacks: [{ name: 'Water Gun', damage: '50', description: '' }],
    weaknesses: [{ type: 'Grass', value: 'x2' }],
    retreatCost: 2,
    description: 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.',
    series: 'Spark Series',
  },
  {
    id: 'kad001',
    name: 'Kadabra',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Kadabra psychic',
    rarity: 'Uncommon',
    type: 'Psychic',
    hp: 80,
    attacks: [{ name: 'Psybeam', damage: '30', description: 'Flip a coin. If heads, the Defending Pokémon is now Confused.' }],
    weaknesses: [{ type: 'Psychic', value: 'x2' }],
    retreatCost: 1,
    description: 'It emits special alpha waves from its body that induce headaches just by being nearby.',
    series: 'Spark Series',
  },

  // Rares
  {
    id: 'venu001',
    name: 'Venusaur',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Venusaur powerful',
    rarity: 'Rare',
    type: 'Grass',
    hp: 150,
    attacks: [{ name: 'Solar Beam', damage: '120', description: '' }],
    weaknesses: [{ type: 'Fire', value: 'x2' }],
    retreatCost: 3,
    description: 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.',
    series: 'Spark Series',
  },
  {
    id: 'blas001',
    name: 'Blastoise',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Blastoise cannons',
    rarity: 'Rare',
    type: 'Water',
    hp: 160,
    attacks: [{ name: 'Hydro Pump', damage: '100', description: 'This attack does 20 more damage for each Water Energy attached to this Pokémon.' }],
    weaknesses: [{ type: 'Grass', value: 'x2' }],
    retreatCost: 3,
    description: 'A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.',
    series: 'Spark Series',
  },

  // Holo Rares
  {
    id: 'char002',
    name: 'Charizard',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Charizard flying',
    rarity: 'Holo Rare',
    type: 'Fire',
    hp: 170,
    attacks: [{ name: 'Fire Spin', damage: '200', description: 'Discard 2 Energy from this Pokémon.' }],
    weaknesses: [{ type: 'Water', value: 'x2' }],
    resistances: [{ type: 'Fighting', value: '-20' }],
    retreatCost: 3,
    description: 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.',
    series: 'Spark Series',
  },
  {
    id: 'alak001',
    name: 'Alakazam',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Alakazam spoons',
    rarity: 'Holo Rare',
    type: 'Psychic',
    hp: 130,
    attacks: [{ name: 'Mind Ruler', damage: '60+', description: 'This attack does 30 more damage for each card in your opponent\'s hand.' }],
    weaknesses: [{ type: 'Psychic', value: 'x2' }],
    retreatCost: 1,
    description: 'Its brain can outperform a super-computer. Its intelligence quotient is said to be 5,000.',
    series: 'Spark Series',
  },
  {
    id: 'drag001',
    name: 'Dragonite',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Dragonite majestic',
    rarity: 'Holo Rare',
    type: 'Dragon',
    hp: 160,
    attacks: [{ name: 'Dragon Tail', damage: '120', description: 'Flip 2 coins. If either is tails, this attack does nothing.' }],
    weaknesses: [{ type: 'Fairy', value: 'x2' }],
    retreatCost: 2,
    description: 'An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.',
    series: 'Mythic Wings',
  },
  {
    id: 'gard001',
    name: 'Gardevoir',
    image: 'https://placehold.co/240x336.png',
    dataAiHint: 'Gardevoir elegant',
    rarity: 'Holo Rare',
    type: 'Fairy',
    hp: 140,
    attacks: [{ name: 'Shining Arcana', damage: '70', description: 'You may attach a basic Energy card from your hand to 1 of your Benched Pokémon.' }],
    weaknesses: [{ type: 'Metal', value: 'x2' }],
    resistances: [{ type: 'Darkness', value: '-20' }],
    retreatCost: 2,
    description: 'It has the power to predict the future. Its power peaks when it is protecting its Trainer.',
    series: 'Mythic Wings',
  },
];

export const allPacks: PokemonPack[] = [
  {
    id: 'spark001',
    name: 'Spark Series Starter Pack',
    series: 'Spark Series',
    image: 'https://placehold.co/200x280.png', // Placeholder pack art
    dataAiHint: 'Pokemon pack electric',
    cardsPerPack: 5,
    rarityDistribution: {
      common: 3,
      uncommon: 1,
      rareSlot: 1, // This slot can be Rare or Holo Rare
    },
    possibleCards: allCards.filter(card => card.series === 'Spark Series').map(card => card.id),
  },
  {
    id: 'mythic001',
    name: 'Mythic Wings Booster',
    series: 'Mythic Wings',
    image: 'https://placehold.co/200x280.png', // Placeholder pack art
    dataAiHint: 'Pokemon pack dragon',
    cardsPerPack: 7,
    rarityDistribution: {
      common: 4,
      uncommon: 2,
      rareSlot: 1,
    },
    possibleCards: allCards.map(card => card.id), // For simplicity, this pack can contain any card
  },
];

export const getCardById = (id: string): PokemonCard | undefined => {
  return allCards.find(card => card.id === id);
};

export const getPackById = (id: string): PokemonPack | undefined => {
  return allPacks.find(pack => pack.id === id);
};
