
import type { PokemonCard } from './types';

// McDonald's Collection 2024 (Pokellector Set ID 410, Set Code M24)
// Image URLs: https://den-cards.pokellector.com/410/{CardName}.M24.{CardNumber}.{UniqueID}.thumb.png
// Pokedex number is the card number X/15 in this specific set.
// 6 Holos, 9 Non-Holos

export const mcDonaldsCollection2024Cards: PokemonCard[] = [
  {
    id: 'mcd-c24-sprigatito-001',
    name: 'Sprigatito',
    image: 'https://den-cards.pokellector.com/410/Sprigatito.M24.1.55521.thumb.png',
    dataAiHint: 'Sprigatito grass cat',
    rarity: 'Holo Rare',
    type: 'Grass',
    series: "McDonald's Collection 2024",
    pokedexNumber: '1/15',
  },
  {
    id: 'mcd-c24-fuecoco-002',
    name: 'Fuecoco',
    image: 'https://den-cards.pokellector.com/410/Fuecoco.M24.2.55523.thumb.png',
    dataAiHint: 'Fuecoco fire crocodile',
    rarity: 'Holo Rare',
    type: 'Fire',
    series: "McDonald's Collection 2024",
    pokedexNumber: '2/15',
  },
  {
    id: 'mcd-c24-quaxly-003',
    name: 'Quaxly',
    image: 'https://den-cards.pokellector.com/410/Quaxly.M24.3.55525.thumb.png',
    dataAiHint: 'Quaxly water duckling',
    rarity: 'Holo Rare',
    type: 'Water',
    series: "McDonald's Collection 2024",
    pokedexNumber: '3/15',
  },
  {
    id: 'mcd-c24-cetoddle-004',
    name: 'Cetoddle',
    image: 'https://den-cards.pokellector.com/410/Cetoddle.M24.4.55527.thumb.png',
    dataAiHint: 'Cetoddle ice whale',
    rarity: 'Holo Rare',
    type: 'Water', // Ice types are often Water in TCG
    series: "McDonald's Collection 2024",
    pokedexNumber: '4/15',
  },
  {
    id: 'mcd-c24-cetitan-005',
    name: 'Cetitan',
    image: 'https://den-cards.pokellector.com/410/Cetitan.M24.5.55529.thumb.png',
    dataAiHint: 'Cetitan ice landwhale',
    rarity: 'Holo Rare',
    type: 'Water', // Ice types are often Water in TCG
    series: "McDonald's Collection 2024",
    pokedexNumber: '5/15',
  },
  {
    id: 'mcd-c24-pikachu-006',
    name: 'Pikachu',
    image: 'https://den-cards.pokellector.com/410/Pikachu.M24.6.55530.thumb.png',
    dataAiHint: 'Pikachu electric mouse',
    rarity: 'Holo Rare',
    type: 'Lightning',
    series: "McDonald's Collection 2024",
    pokedexNumber: '6/15',
  },
  {
    id: 'mcd-c24-pawmi-007',
    name: 'Pawmi',
    image: 'https://den-cards.pokellector.com/410/Pawmi.M24.7.55531.thumb.png',
    dataAiHint: 'Pawmi electric mouse',
    rarity: 'Common',
    type: 'Lightning',
    series: "McDonald's Collection 2024",
    pokedexNumber: '7/15',
  },
  {
    id: 'mcd-c24-pawmo-008',
    name: 'Pawmo',
    image: 'https://den-cards.pokellector.com/410/Pawmo.M24.8.55532.thumb.png',
    dataAiHint: 'Pawmo electric mouse evolution',
    rarity: 'Common',
    type: 'Lightning',
    series: "McDonald's Collection 2024",
    pokedexNumber: '8/15',
  },
  {
    id: 'mcd-c24-pawmot-009',
    name: 'Pawmot',
    image: 'https://den-cards.pokellector.com/410/Pawmot.M24.9.55533.thumb.png',
    dataAiHint: 'Pawmot electric fighting mouse',
    rarity: 'Common',
    type: 'Lightning',
    series: "McDonald's Collection 2024",
    pokedexNumber: '9/15',
  },
  {
    id: 'mcd-c24-klawf-010',
    name: 'Klawf',
    image: 'https://den-cards.pokellector.com/410/Klawf.M24.10.55534.thumb.png',
    dataAiHint: 'Klawf rock crab',
    rarity: 'Common',
    type: 'Fighting', // Rock types are often Fighting in TCG
    series: "McDonald's Collection 2024",
    pokedexNumber: '10/15',
  },
  {
    id: 'mcd-c24-flittle-011',
    name: 'Flittle',
    image: 'https://den-cards.pokellector.com/410/Flittle.M24.11.55520.thumb.png',
    dataAiHint: 'Flittle psychic ostrich',
    rarity: 'Common',
    type: 'Psychic',
    series: "McDonald's Collection 2024",
    pokedexNumber: '11/15',
  },
  {
    id: 'mcd-c24-espathra-012',
    name: 'Espathra',
    image: 'https://den-cards.pokellector.com/410/Espathra.M24.12.55524.thumb.png',
    dataAiHint: 'Espathra psychic ostrich evolution',
    rarity: 'Common',
    type: 'Psychic',
    series: "McDonald's Collection 2024",
    pokedexNumber: '12/15',
  },
  {
    id: 'mcd-c24-cyclizar-013',
    name: 'Cyclizar',
    image: 'https://den-cards.pokellector.com/410/Cyclizar.M24.13.55526.thumb.png',
    dataAiHint: 'Cyclizar dragon lizard',
    rarity: 'Common',
    type: 'Dragon',
    series: "McDonald's Collection 2024",
    pokedexNumber: '13/15',
  },
  {
    id: 'mcd-c24-tandemaus-014',
    name: 'Tandemaus',
    image: 'https://den-cards.pokellector.com/410/Tandemaus.M24.14.55528.thumb.png',
    dataAiHint: 'Tandemaus couple mice',
    rarity: 'Common',
    type: 'Colorless',
    series: "McDonald's Collection 2024",
    pokedexNumber: '14/15',
  },
  {
    id: 'mcd-c24-maushold-015',
    name: 'Maushold',
    image: 'https://den-cards.pokellector.com/410/Maushold.M24.15.55535.thumb.png',
    dataAiHint: 'Maushold family mice',
    rarity: 'Common',
    type: 'Colorless',
    series: "McDonald's Collection 2024",
    pokedexNumber: '15/15',
  },
];
